- package.json
- src/README.md
**Summary**
- This PR adds a project readme.
- Added README.md
> chore: add project readme

- .github/workflows/publish.yml
Closes #
**Summary**
- Fix name of main branch in publish action
> chore: fix publish action

- src/design/colors-tokens/ColorCard.tsx
- src/design/colors-tokens/_color-card.scss
- src/design/colors-tokens/color-tokens.mdx
**Summary**
- Update the color tokens page with more color tokens.
> feat(colortokens): add color token

- package.json
Closes #
**Summary**
fix issue with private repo default
> fix(packagejson): fix issue with private repo default

- package.json
Closes #
**Summary**
- summary_here
- items_here
- tests here
- tests here
> fix: fix deployment

- .github/workflows/publish.yml
- package.json
**Summary**
- add build step to publish action
> fix(publish): add build step to publish action

- package.json
Closes #
**Summary**
- tweaking config settings for published output.
> fix(packagejson): change config for publishing

- package.json
> fix(packagejson): fix errors in publish config

- package.json
Closes #
**Summary**
- summary_here
- items_here
- tests here
- tests here
> fix(config): last change broke. removing pkgRoot

- src/design/colors-tokens/ColorCard.tsx
- src/styles.scss
**Summary**
- There were issues with import path used in main stylesheet. There was also a bug in our ColorCard component when a gradient was passed.
> fix(style): fix path issue and bug in storybook

- package.json
**Summary**
- Fixing the script that cleans and builds the production instance of storybook.
> chore: fix storybook build script

- .github/workflows/build.yml
- README.md
**Summary**
- Update README and the build actions name
**Changes**:
- Add netlify tag to README.md
- Changed import instructions on README.md
- Changed the name of the github build action
> Update README and the build actions name

- .github/PULL_REQUEST_TEMPLATE.MD
- package-lock.json
- package.json
- src/components/Button/Button.tsx
- src/pages/Page.tsx
**Summary**
- Needed to fix some config files for semantic-release as the changelog was not being added. 
- updated package.json with new config options
- added a changelog package to the repo
> Config update

- src/components/HeroBanner/_heroBanner.scss
Closes [WEB-8508](https://phillipsauctions.atlassian.net/browse/WEB-8508)
**Summary**
Updates font usage for different text types within the HeroBanner component
- Updated h1 tags to use DistinctDisplay font family instead of DistinctText font family
- Updated styles to allow h1 span, and p tags to continue using the DistinctText font family
- Verify that the main h1 tag is using the DistinctDisplay font family
- Verify that the pre-head and post-head values are using the DistinctText font family
- tests here
> Web 8508 hero banner component

- src/index.ts
Flatpickr is crashing our web build. Removing export until we can lock down the seldon repo version. 
> fix(datepicker): remove export until we can figure out flatpickr error

- CHANGELOG.md
- src/components/ViewingsList/ViewingsList.tsx
- src/components/ViewingsList/ViewingsListCard.tsx
- src/components/ViewingsList/ViewingsListCardForm.tsx
Closes #
**Summary**
- Updated remaining interfaces for email fields
- Added Email fields to `ViewingsList` and `ViewingsListCard`, alphabetized interface and props in `ViewingListCardForm`
- Email fields should now be replaceable with i18n object
> L3-410 Chinese translations fixes II

- src/design/colors-tokens/_color-card.scss
- src/design/colors-tokens/color-tokens.mdx
- src/design/type-tokens/_text-showcase.scss
- src/design/type-tokens/type-tokens.mdx
- src/scss/_type.scss
- src/scss/_typography.scss
- src/scss/_vars.scss
- src/story-styles.scss
Closes [L3-1461](https://phillipsauctions.atlassian.net/browse/L3-1461)
**Summary**
Add type tokens and mixins to be used for all component building. Also added docs in the form of a design story
- updated Color token page to use new tokens. 
- added needed styles to the stylesheet for color token
- added a text-showcase css file to add styles for the doc page
- added the type-tokens markdown page
- added type partial which defines the type mixins
- updated typography partial to use same font name for each declaration. This way we do not have to swap font-family to changes style.
- also updated the main body font stack to match the change to Montserrat
- added type token variables in vars partial
- added common story styles to story …
> feat: add type tokens

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.MD
- .husky/pre-push
- CHANGELOG.md
- package-lock.json
- src/design/type-tokens/type-tokens.mdx
**Summary**
- Adds additional Git configuration and a husky hook to run quality checks on push
- Add scott to codeowners
- Update the PR Template to add screenshot
- Add Push check on husky
- Paste the PR Template into a new PR and make sure it renders correctly in preview mode
- Add screenshots for Before and After to the table and make sure they work
- Validate that pushing a change runs the husky pre-push hook
- Code owners and PR Template changes cannot 
- Quality checks should pass
> docs: update PR template

- src/design/colors-tokens/_color-card.scss
- src/design/colors-tokens/color-tokens.mdx
- src/design/type-tokens/type-tokens.mdx
- src/scss/_vars.scss
[L3-1463](https://phillipsauctions.atlassian.net/browse/L3-1463)
**Summary**
- Aligning the color token values with changes made in the design system as well as ensuring all tokens needed for "About Us" are present.
- Fixed positioning of copied text in `src/design/colors-tokens/_color-card.scss`
- Changed values in story documentation to match the ticket linked in `src/design/colors-tokens/color-tokens.mdx`
- Attempt to check in Token format change one last itme in `src/design/type-tokens/type-tokens.mdx`
- Change values to match ticket and mapped those changed in case they are being used elsewhere in …
> Color check

- src/components/ViewingsList/ViewingsListCardForm.tsx
- src/design/type-tokens/type-tokens.mdx
[L3-382](https://phillipsauctions.atlassian.net/browse/L3-382)
| <img width="548" alt="image" src="https://github.com/PhillipsAuctionHouse/seldon/assets/1590966/2e53fe03-48ce-4bf2-badc-022d87c7030a"> | <img width="545" alt="image" src="https://github.com/PhillipsAuctionHouse/seldon/assets/1590966/6d0c02d6-583f-43f4-bd79-234697e95c7d"> |
**Summary**
This PR adds changes for request by product owners to move the order of the viewing inputs.
- Change source order for url input - `src/components/ViewingsList/ViewingsListCardForm.tsx`
- Verify that the source order has changed in deploy preview.
**Things to look for during …
> L3-382 - Change input order

- .github/CODEOWNERS
- .github/auto-merge.yml
- .github/dependabot.yml
- .github/workflows/auto-merge.yml
- src/design/type-tokens/type-tokens.mdx
#L3-1838
[L3-1838](https://phillipsauctions.atlassian.net/browse/L3-1838)
**Summary**
It's an implementation of dependabot and auto-merge in seldon like the one here in `phillips-public-remix`
[this](https://github.com/PhillipsAuctionHouse/phillips-public-remix/pull/5)
- See linked PR
- Must be merged unfortunately to test
N/A
N/A
[L3-1838]: https://phillipsauctions.atlassian.net/browse/L3-1838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> L3-1838(dependabot): add dependabot to repo

- .eslintrc.cjs
- src/components/Link/Link.stories.tsx
- src/components/Link/Link.test.tsx
- src/components/Link/Link.tsx
- src/components/Link/utils.test.ts
- src/components/Link/utils.ts
- src/components/LinkBlock/LinkBlock.test.tsx
- src/components/LinkBlock/LinkBlock.tsx
- src/components/LinkList/_linkList.scss
- src/index.ts
- src/scss/_utils.scss
- tsconfig.json
[L3-1468](https://phillipsauctions.atlassian.net/browse/L3-1468)
| <img width="1728" alt="image" src="https://github.com/PhillipsAuctionHouse/seldon/assets/6663002/3101bf10-c774-450b-8e7d-a67ea0bdfde6"> | <img width="1703" alt="image" src="https://github.com/PhillipsAuctionHouse/seldon/assets/6663002/1b0c9b13-db18-4e96-8891-e4fd0ef1f5a4"> |
**Summary**
There was a bug with how I'm doing responsive media queries at the max breakpoint for the linklist component.  We're also migrating the LinkVariants const to an enum as it has better typing support.
- change(Link): change const to enum
- change(utils): make the `media` mixin more explicit that it's using `min-width` …
> fix(linklist): fix incorrect responsive layout

- src/utils/index.tsx
(https://phillipsauctions.atlassian.net/browse/L3-2075)
**Summary**
Chore: L3-2065 Remove Nullish Coalescing Operators polyfill in Seldon have already been merged.
However the title and commit message was incorrect.
Added a comment with this PR in order to publish a new version later.
New Components
> fix: L3-2075 nullishCoalescing polyfill

- src/index.ts
- vite.config.ts
[L3-2289](https://phillipsauctions.atlassian.net/browse/L3-2289)
| ![image](https://github.com/PhillipsAuctionHouse/seldon/assets/1590966/cb74e911-490d-4b08-9c1a-13053dceb219)| ![image](https://github.com/PhillipsAuctionHouse/seldon/assets/1590966/1fbfa4e3-a602-4f7f-9cab-85fd0124d56a) |
**Summary**
Import the the utils file into our index entry file.
- Change import to include other util functions. 
- Run the build command locally and make sure you see the `emailValidation` function being exported. 
New Components
[L3-2289]: https://phillipsauctions.atlassian.net/browse/L3-2289?atlOrigi …
> fix(build): L3-2289 - add entry for utils

- src/components/Footer/_footer.scss
- src/components/GridItem/_gridItem.scss
- src/components/HeroBanner/_heroBanner.scss
- src/components/Link/Link.tsx
- src/components/Link/_link.scss
- src/components/LinkList/_linkList.scss
- src/components/Social/_social.scss
- src/components/SplitPanel/_splitPanel.scss
- src/components/Subscribe/_subscribe.scss
- src/components/Text/types.ts
- src/components/Text/utils.test.ts
- src/components/Text/utils.ts
- src/design/breakpoint-tokens/breakpoint-tokens.mdx
- src/design/grid-tokens/grid-tokens.mdx
- src/design/type-tokens/_text-showcase.scss
- src/design/type-tokens/type-tokens.mdx
- src/scss/_type.scss
- src/scss/_utils.scss
- src/scss/_vars.scss
[L3-378](https://phillipsauctions.atlassian.net/browse/L3-378)
Added new breakpoints story:
**Summary**
These changes are feedback from the design review of the About Us page with @RyanOlanoPHILLIPS @davidicus and @adietrich3074 
This updates token names for breakpoints, makes some changes to the Text component to better render blockquotes, makes some small tweaks to the semantic HTML that gets rendered.  
- change(HeroBanner): use variables for breakpoints not hardcoded
- change(*.scss): update token names
- add(breakpoint-tokens): simple breakpoint story (outside of the Grid tokens story)
- change(Text): changes to semantic html and padding for the variants …
> feat(text): L3-378 update text component and text and breakpoint tokens

- src/components/Button/Button.tsx
- src/components/Footer/Footer.tsx
- src/components/Grid/Grid.tsx
- src/components/GridItem/GridItem.tsx
- src/components/HeroBanner/HeroBanner.tsx
- src/components/Input/Input.tsx
- src/components/Link/Link.tsx
- src/components/LinkBlock/LinkBlock.tsx
- src/components/LinkList/LinkList.tsx
- src/components/Row/Row.tsx
- src/components/Select/Select.tsx
- src/components/Social/Social.tsx
- src/components/Subscribe/Subscribe.tsx
- src/components/Text/Text.tsx
[L3-2028](https://phillipsauctions.atlassian.net/browse/L3-2028)
**Summary**
Added overview jsdoc comment with Figma link to all components.
- Added storybook and figma link to all represented components in Figma
- Hover over the component name.
- Click on the Figma link.
- Verify that the Figma design matches the component.
- Locate the Dev Resources section and click on the link.
- Verify that the new page matches the Figma page.
New Components
[L3-2028]: …
> docs(storybook): L3-2028 added links to figma and storybook

- src/components/Modal/Modal.test.tsx
- src/components/Modal/Modal.tsx
- src/index.ts
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-2144)
**Summary**
Small changes to adapt new `Modal` component for Remix project
- Changed the way we are handling `ariaHideApp` for Modal
- Added tests to verify that area-hide is working
- Exported  SubscriptionState type
- aria-hide has to be true for `body` once Modal is open
New Components
> feat(modal): L3-2144 changed modal appElementSelector

- src/index.ts
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-2144)
| none | none  |
**Summary**
Changed export type of SubscriptionState because It's impossible to use Enum when exported as type;
- fix(index.ts): changed export type of subscription state
- Test that `SubscriptionState` is imported as an Enum
- None old functionality touched
New Components
> fix(index.ts): L3-2144 changed export type of subscription state

- .github/workflows/auto-merge.yml
- .github/workflows/validate-pr.yaml
- commitlint.config.js
[L3-2357](https://phillipsauctions.atlassian.net/browse/L3-2357)
**Summary**
Seldon equivalent for this PR:
https://github.com/PhillipsAuctionHouse/phillips-public-remix/pull/96
New Components
[L3-2357]: https://phillipsauctions.atlassian.net/browse/L3-2357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci(prtitle): L3-2357 relax enforcement for dependabot PRs

- .eslintignore
- .eslintrc.cjs
- package-lock.json
- package.json
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/components/DatePicker/DatePicker.stories.tsx
- src/components/DatePicker/DatePicker.test.tsx
- src/components/Input/Input.test.tsx
- src/components/LinkList/LinkList.test.tsx
- src/components/Select/Select.test.tsx
- src/components/Select/Select.tsx
- src/components/ViewingsList/ViewingsList.test.tsx
- src/components/ViewingsList/ViewingsList.tsx
- src/components/ViewingsList/ViewingsListCard.tsx
- src/design/colors-tokens/ColorCard.tsx
- src/pages/Page.tsx
[L3-2356](https://phillipsauctions.atlassian.net/browse/L3-2356)
**Summary**
We need to enhance our eslint rules to catch more errors at coding time.  Specifically I want to add some more best practice React ones, async/await promise enforcement and validation of boolean property naming conventions
- change(eslint): add react/recommended rules, `react/boolean-prop-naming`, `require-await` and `@typescript-eslint/no-floating-promises`
- change(Button*/ViewingsListCard): I did need to rename a few props but I have noticed that no external consumers are using them yet in `phillips-public` or `phillips-public-remix` so I think we can get away with that small change without putting out the major version.
**Acceptance Test …
> fix(booleanProps): L3-2356 eslint rules to enforce boolean props

- src/components/ViewingsList/ViewingsList.test.tsx
- src/utils/constants.ts
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-2528)
| N/A | N/A |
**Summary**
Fixed test that was falling on slower laptop. 
**Context:** On the fast laptop test was about 4000ms. Default timeout for unit test is 5000ms, so test was falling on slower laptop exceeding 5000ms.
- feat(constants): added file
- feat(ViewingsList.test.tsx): added new option
- all test have to pass
- ![image](https://github.com/PhillipsAuctionHouse/seldon/assets/26413122/19fb817e-6d4d-4982-9237-e …
> test(ViewingsList): L3-2528 fixed test with long timeout

- src/components/HeroBanner/_heroBanner.scss
[L3-2178](https://phillipsauctions.atlassian.net/browse/L3-2178)
| <img width="441" alt="image" src="https://github.com/PhillipsAuctionHouse/seldon/assets/1590966/6b04d463-4905-46dc-b67b-7d188014a449"> | <img width="465" alt="image" src="https://github.com/PhillipsAuctionHouse/seldon/assets/1590966/923b7ac3-4efa-46ef-be52-21831d95ac00"> |
**Summary**
Swap image placement at smaller breakpoints for the Hero Banner component
- updated styles in `src/components/HeroBanner/_heroBanner.scss`
- Make sure image is below text at the smallest breakpoint.
- Hero banner component should look normal at larger …
> feat(herobanner): L3-2178 - swap image placement on smaller breakpoints

- src/components/Subscribe/Subscribe.test.tsx
- src/components/Subscribe/Subscribe.tsx
- src/components/Subscribe/types.ts
[L3-2525](https://phillipsauctions.atlassian.net/browse/L3-2525)
| ![image](https://github.com/PhillipsAuctionHouse/seldon/assets/26413122/d25268c9-aa82-429e-9a11-a4a657188d54) | ![image](https://github.com/PhillipsAuctionHouse/seldon/assets/26413122/4299e588-cc5a-4cf2-bfa9-85ae2d9f2cf4) |
**Summary**
Added error type to `SubscriptionState`
- feat(src/components/Subscribe/Subscribe.tsx): added new prop and changed the invalid state handling
- feat(src/components/Subscribe/types.ts): added new type
- Check that when subscriptionState is error, the text 'An error occurred. Please try again.' is visible and the input is red …
> feat(types): L3-2525 added error type to SubscriptionState

- src/components/Navigation/NavigationItem/_navigationItem.scss
- vite.config.ts
[L3-2823](https://phillipsauctions.atlassian.net/browse/L3-2823)
**Summary**
Reverted vite config change, removed before styles on nav links to allow normal link functionality
Header direct nav links should function normally now
New Components
[L3-2823]: https://phillipsauctions.atlassian.net/browse/L3-2823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(header): L3-2823 Fix For Direct Nav Links

- src/components/Header/Header.stories.tsx
- src/components/Header/Header.test.tsx
- src/components/Header/Header.tsx
- src/components/Header/_header.scss
- src/components/Input/_input.scss
- src/components/Navigation/NavigationItem/_navigationItem.scss
- src/components/Navigation/NavigationList/NavigationList.tsx
- src/components/Navigation/NavigationList/_navigationList.scss
- src/components/Navigation/_navigation.scss
- src/components/Search/_search.scss
- src/components/UserManagement/UserManagement.tsx
- src/components/UserManagement/_userManagement.scss
- src/scss/_utils.scss
- src/scss/_vars.scss
[L3-2815](https://phillipsauctions.atlassian.net/browse/L3-2815)
| description | Missing Bottom Border and overlaying the page content |
| ![image](https://github.com/user-attachments/assets/198e519e-6ba7-46e3-ace8-89c8e5d19c70) | ![image](https://github.com/user-attachments/assets/c4fa4304-c6bc-434f-9857-e38fd6020c20) |
| description | Scroll bar and alignment issue on mobile menu |
| ![image](https://github.com/user-attachments/assets/39d803fb-fd06-4ffe-8a0c-bfba3268def4) | ![image](https://github.com/user-attachments/assets/fac78ef9-efab-432d-93d2-15a2c6bc3724) |
| description | Center the view upcoming auctions |
| ![image](https://github.com/user-attachments/assets/41ec4f67-c9f4-422c-88ae-fb34dbb9a38e) | …
> fix(header): L3-2815 fix minor header style issues

- src/components/Button/Button.tsx
- src/components/Button/_button.scss
[L3-2287](https://phillipsauctions.atlassian.net/browse/L3-2287)
| ![image](https://github.com/user-attachments/assets/596227a0-72e5-45bf-88ba-873ba61e0c53) | 
|
**Summary**
Add disabled state to button component
- Button.tsx:  add prop to control disabled state for button 
- _button.scss: add styling for disabled state
- In storybook, toggle the new `isDisabled` prop to be true, see that all button variants have the same disabled styling
**Things to look for …
> feat(button): L3-2287 add disabled state for button

- src/components/Header/Header.stories.tsx
- src/components/UserManagement/UserManagement.tsx
- src/components/UserManagement/_userManagement.scss
[L3-2945](https://phillipsauctions.atlassian.net/browse/L3-2945)
| https://github.com/user-attachments/assets/3e6e8ebe-e2b1-4298-be29-9d4c6bb6fec1 | https://github.com/user-attachments/assets/efa9ef4b-9a5c-4bac-9fcd-89e8b71cb880 |
**Summary**
See the videos above but after selecting a language, the language switcher stuck around
- change(usermanagement): remove focus so the language switcher will disappear after leaving
- In the header story select Chinese as the language and then mouse off the language switcher.  It should totally disappear
- Check the UserManagement story too
- Make sure the …
> fix(header): L3-2945 language overlay should disappear correctly

- src/components/LinkList/LinkList.test.tsx
- src/components/LinkList/LinkList.tsx
[L3-2973](https://phillipsauctions.atlassian.net/browse/L3-2973)
**Summary**
The check in `LinkList` for `LinkBlock` children was too restrictive because it wouldn't allow me to pass a custom component that I wrapped around a `LinkBlock` component.  It would skip rendering my `LinkBlockLocalized` component entirely so I've removed the check.  
- change(LinkList): render any child component, not just `LinkBlock`
- Validate that any child component can render by adding it to a story
- Sniff test the existing LinkList story.
New Components
[L3-2973]: …
> fix(linklist): L3-2973 relax the linkblock child requirement 

- package-lock.json
- package.json
- src/components/Button/Button.tsx
- src/components/Drawer/Drawer.stories.tsx
- src/components/Drawer/Drawer.test.tsx
- src/components/Drawer/Drawer.tsx
- src/components/Drawer/_drawer.scss
- src/components/Drawer/index.ts
- src/components/Subscribe/_subscribe.scss
- src/index.ts
- src/scss/_vars.scss
- src/styles.scss
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-3071)
| ![image](https://github.com/user-attachments/assets/2a660ebf-6b14-483f-8216-94fb00b59ef5) | ![image](https://github.com/user-attachments/assets/777603e3-1874-497d-8813-4ea50a52754e) |
**Summary**
Added drawer component using Radix Primitivis  
- Additions, Changes, and Radix primitives
- verify that drawer opens on button click
- verify that content of drawer visible
- verify that drawer full size on phone
- verify that drawer closes hitting both: overlay and closing icon 
- (Optional) Add verification steps to make sure this PR …
> feat(drawer): L3-3071 added drawer component

- src/components/Accordion/AccordionItem.tsx
- src/components/Footer/Footer.stories.tsx
- src/components/Footer/Footer.tsx
- src/components/Footer/_footer.scss
- src/components/Social/Social.tsx
- src/components/Social/_social.scss
**L3-2980: Footer style/UX refactor for updated Figma**
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-2980)
| ![image](https://github.com/user-attachments/assets/883284dc-900c-46e8-92d8-aad09dead15e) | ![image](https://github.com/user-attachments/assets/2b7ba229-d90a-4444-bf20-9412476a4ffb) |
**Summary**
Refactored mobile and desktop version of footer to match new Figma's design
- fix(AccordionItem.tsx): added quick fix to add controlled state to component
- feat(Footer.tsx): removed nav, added structural changes
- feat(Social.tsx): structural changes
- Desktop version: links are visible
- Desktop version: links have …
> feat(footer): L3-2980 footer redesign

- src/components/Input/Input.tsx
- src/components/Input/_input.scss
- src/components/Subscribe/Subscribe.tsx
- src/components/Subscribe/_subscribe.scss
[L3-3126](https://phillipsauctions.atlassian.net/browse/L3-3126)
| ![image](https://github.com/user-attachments/assets/44e89d55-dd57-4991-980d-df8b5a40b690) | ![image](https://github.com/user-attachments/assets/4d1e509e-aec5-45e2-99f6-090d6b957e41) |
**Summary**
Changed styles to follow new Figma's design
- feat(_subscribe.scss): added new styles
- feat(Subscribe.tsx): added privacy text
- verify that subscribe states are working
- verify that privacy text is visible
- verify that signup button is full width in mobile view
- (Optional) Add verification steps to make sure this PR doesn't break old …
> feat(subscribe): L4-3126 changed styles

- .eslintrc.cjs
- eslint-local-rules.cjs
- package-lock.json
- package.json
- src/components/Footer/Footer.stories.tsx
- src/components/Footer/Footer.tsx
- src/components/Footer/_footer.scss
- src/components/Header/Header.test.tsx
- src/components/Modal/Modal.stories.tsx
- src/components/Navigation/NavigationList/NavigationList.test.tsx
- src/components/Social/_social.scss
- src/components/ViewingsList/ViewingsListCard.tsx
- src/components/ViewingsList/ViewingsListCardForm.tsx
[L3-2980](https://phillipsauctions.atlassian.net/browse/L3-2980)
**Summary**
Added two different footers for mobile and desktop view
- feat(_footer.scss): added styles for desktop footer
- feat(Footer.stories.tsx): restructured footer example
- verify that mobile footer is showing accordion
- verify that desktop footer is showing open links
New Components
[L3-2980]: …
> feat(footer): L3-2980 footer mobile redesign

- src/components/Search/Search.tsx
[L3-2524](https://phillipsauctions.atlassian.net/browse/L3-2524)
**Summary**
Added submitting state to match what states can be returned by fetcher
- Added submitting state
New Components
[L3-2524]: https://phillipsauctions.atlassian.net/browse/L3-2524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(search): L3-2524 Search API

- .releaserc.json
- package-lock.json
- src/components/Navigation/NavigationItem/NavigationItem.tsx
- src/design/grid-tokens/grid-tokens.mdx
- src/scss/_utils.scss
[L3-2994](https://phillipsauctions.atlassian.net/browse/L3-2994)
| ![image](https://github.com/user-attachments/assets/7168ab73-4933-4510-8ddc-e42865b0d4e8) | ![image](https://github.com/user-attachments/assets/0f2d740c-eaab-4c30-9804-d15a95d9e277) |
**Summary**
Increases the vertical spacing of the Grid component to match the new About Us style
- change(NavigationItem): Allow to pass custom elements (like Remix Link)
- change(grid-tokens): update tokens example
- change(utils): add row gap
- Verify the grid-tokens story and the Grid story
- (Optional) Add verification steps to make sure this PR …
> fix(grid): L3-2994 updates needed to grid styles

- src/components/Footer/Footer.stories.tsx
- src/components/Footer/Footer.tsx
- src/components/Footer/_footer.scss
- src/components/Link/_link.scss
- src/components/Social/Social.tsx
- src/components/Social/_social.scss
- src/scss/_type.scss
- src/scss/_vars.scss
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-3126)
| ![image](https://github.com/user-attachments/assets/9f0b6edb-a3ad-45db-9a3d-3383de9e5c0d) | ![image](https://github.com/user-attachments/assets/e14f091b-c5fc-4288-b4a4-c4f71e91bed0) |
**Summary**
Added new footer update
- feat(Footer.tsx): removed split panel
- feat(_footer.scss): removed unnecessary styles
- feat(Social.tsx): changed text tag
- verify that desktop version is not in accordion
- verify that mobile version is in accordion
- verify that links containers have the same width on desktop
- verify that tablet view has max-width for footer …
> feat(footer): L3-3126 3rd footer update

- src/components/Accordion/_accordion.scss
[L3-3439](https://phillipsauctions.atlassian.net/browse/L3-3439)
| ![L3-3439 fix - before](https://github.com/user-attachments/assets/c4c73ac4-81ca-48b7-9489-82964f377df5) | ![L3-3439 fix - after](https://github.com/user-attachments/assets/db1505c5-04ab-4411-93be-a5a6687c8940) |
**Summary**
I needed to update the classes to use the prefix variable instead of hardcoding it
* src/components/Accordion/_accordion.scss
* Updated classes to use prefix variable instead of hardcoded `phillips`
Verify accordion buttons only appear one-at-a-time and work properly when opening and closing panels
- (Optional) Add …
> fix(scss): L3-3439 use prefix for accordion classes

- src/components/Accordion/_accordion.scss
- src/components/Drawer/_drawer.scss
- src/components/Footer/_footer.scss
- src/components/Social/_social.scss
- src/scss/_vars.scss
[L3-3126](https://phillipsauctions.atlassian.net/browse/L3-3126)
| ![image](https://github.com/user-attachments/assets/0d8914db-9f96-4237-ad3b-da9a36b8fc47) | ![image](https://github.com/user-attachments/assets/f0af1058-edcb-4bab-8ea3-bce75126c234) |
**Summary**
Small footer adjustments and drawer animation
- fix(_accordion.scss): fixed jump on item open
- feat(_drawer.scss): matched animation with PP's drawer animation + added on close animation
- fix(_footer.scss): isolated links styles to remove default styles from icons
- feat(_vars.scss): added new variables
- verify that icons have no underline style
- verify that …
> feat(footer): L3-3126 footer fixes and animation updates

- src/components/Footer/_footer.scss
[L3-3126](https://phillipsauctions.atlassian.net/browse/L3-3126)
**Summary**
Added some spacings
- feat(footer.scss): added missing spacings
- Desktop: Verify that spacing between header and links according figma
- Mobile: Verify that when accordion open space bellow links si according figma
New Components
[L3-3126]: https://phillipsauctions.atlassian.net/browse/L3-3126?atlOrigin=eyJp …
> feat(footer): L3-3126 footer adjustments

- src/components/Modal/_modal.scss
- src/components/Search/_search.scss
- src/scss/_vars.scss
[L3-3616](https://phillipsauctions.atlassian.net/browse/L3-3616)
| ![image](https://github.com/user-attachments/assets/634f5dec-b822-4b1b-92a5-63b12bd89ec1) | ![image](https://github.com/user-attachments/assets/b0689f47-2368-4e5e-a089-bddc71f442cb) |
**Summary**
fixed qr modal and heading 3
- feat(src/scss/_vars.scss): added z-index variable
New Components
> feat(_modal): L3-3616 fixed qr modal and heading 3

- src/components/Accordion/AccordionItem.tsx
- src/components/Accordion/_accordion.scss
[L3-3127](https://phillipsauctions.atlassian.net/browse/L3-3127)
| NO VISUAL CHANGE | NO VISUAL CHANGE |
**Summary**
Changed format of accordion icons from image to svg
- feat(src/components/Accordion/AccordionItem.tsx): changed format
- feat(src/components/Accordion/_accordion.scss): removed default svg behavior 
- verify that open/close icons on accordion are the same as on https://phillips-seldon.netlify.app/?path=/docs/components-accordion--overview
**Things …
> feat(accordion): L3-3127 fixed accordions for Phillips Public

- src/components/Header/Header.stories.tsx
- src/components/Header/_header.scss
- src/components/UserManagement/_userManagement.scss
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-3694)
| ![image](https://github.com/user-attachments/assets/1dc77dd1-87bc-4592-9917-6414ab2bf85c) | ![image](https://github.com/user-attachments/assets/bb65a110-3286-46c8-9e8e-2341043557d3) |
**Summary**
Safari on iOS adds paddings inside the button by default and was shrinking the icon. 
- change(header.scss): move the logo down a bit on mobile to better align
- change(userManagement.scss): make the button and icon bigger on mobile
- Test at the mobile breakpoint (ideally npm linking into Remix)
- If you have an iPhone hit the seldon link in preview or use …
> fix(login): L3-3694 increase mobile icon size

- src/components/Text/Text.stories.tsx
- src/components/Text/Text.test.tsx
- src/components/Text/Text.tsx
- src/components/Text/_text.scss
[L3-3572](https://phillipsauctions.atlassian.net/browse/L3-3572)
| ![image](https://github.com/user-attachments/assets/ae23addb-e5a3-4d0b-b8ab-8f2c6a291834) | ![image](https://github.com/user-attachments/assets/614ebff4-0e3e-400c-8d4f-349c9fb18cc6) |
**Summary**
added superscript prop to Text component
- src/components/Text/Text.stories.tsx: added new sub component
- src/components/Text/Text.tsx: added new prop
- go to storybook, open Text's component overview, verify that when you add text to `superScript` prop small text shows after main text
- go to storybook, open sub component inside Text component called `Super …
> feat(Text): L3-3572 added superscript prop

- src/components/Button/_button.scss
- src/components/Drawer/Drawer.tsx
- src/components/Modal/Modal.tsx
- src/components/Pagination/Pagination.tsx
- src/patterns/Social/Social.tsx
[L3-3801](https://phillipsauctions.atlassian.net/browse/L3-3801)
| Before | After | ![image](https://github.com/user-attachments/assets/078d0f0b-925f-4c5a-b319-eeaa474607ab) |
**Summary**
- Ensure new button variant styling plays nice with other components 
- Update secondary and ghost styling so special hover works everywhere
- Specify or update component variants where needed 
Components in storybook, using `IconButton`:
- Drawer
- Modal
- Pagination 
Using `Button`:
- Content Peek 
- Social / footer 
- Subscribe
- ViewingsList / ViewingsListCard
- (Optional) Add …
> fix(button): L3-3801 fix button styling issues in other components

- src/componentStyles.scss
- src/components/PageContentWrapper/PageContentWrapper.stories.tsx
- src/components/PageContentWrapper/PageContentWrapper.test.tsx
- src/components/PageContentWrapper/PageContentWrapper.tsx
- src/components/PageContentWrapper/_pageContentWrapper.scss
- src/components/PageContentWrapper/index.ts
- src/components/Row/_row.scss
- src/index.ts
[L3-3860](https://phillipsauctions.atlassian.net/browse/L3-3860)
**Summary**
- Create wrapper component to have unified padding for content on all Remix pages
- Create new component files
- See storybook 
New Components
[L3-3860]: https://phillipsauctions.atlassian.net/browse/L3-3860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(pageContentWrapper): L3-3860 Create Wrapper component for Seldon

- config/vitest/setupTest.ts
- package-lock.json
- package.json
- src/componentStyles.scss
- src/components/Carousel/Carousel.stories.tsx
- src/components/Carousel/Carousel.test.tsx
- src/components/Carousel/Carousel.tsx
- src/components/Carousel/CarouselContent.tsx
- src/components/Carousel/CarouselDots.tsx
- src/components/Carousel/CarouselItem.tsx
- src/components/Carousel/_carousel.scss
- src/components/Carousel/index.ts
- src/components/Carousel/types.ts
- src/components/Carousel/utils.ts
- src/components/Modal/_modal.scss
- src/index.ts
[L3-3145](https://phillipsauctions.atlassian.net/browse/L3-3145)
**Mobile**
https://github.com/user-attachments/assets/cac28f88-5724-4e58-9a3e-f69a56d1bba9
**Desktop**
https://github.com/user-attachments/assets/f855d723-8351-4ddb-bb4e-cabaa387082a
**Summary**
Composable Carousel component suite in Seldon
Still awaiting: overflow behavior from design, loading state, null state
- Carousel, CarouselContent, CarouselItem, and CarouselDots components
- Add step by step instructions on how to …
> feat(carousel): L3-3145 carousel component in seldon

- src/site-furniture/Footer/_footer.scss
[L3-3865](https://phillipsauctions.atlassian.net/browse/L3-3865)
| ![image](https://github.com/user-attachments/assets/1c5dd385-1ef6-416c-baf5-bb38bb59adec) | ![image](https://github.com/user-attachments/assets/1230dcb4-821f-49af-866a-5bab20d7b6c2) |
**Summary**
Changed logo size in Footer
- src/site-furniture/Footer/_footer.scss: changed height of footer's logo
- verify that logo is the same as figma
New Components …
> feat(footer): L3-3865 logo size change

- src/components/Accordion/_accordion.scss
- src/patterns/Social/_social.scss
[L3-3723](https://phillipsauctions.atlassian.net/browse/L3-3723)
| ![image](https://github.com/user-attachments/assets/d4c24c02-06f3-4713-a3e6-e467b02ee4f2) | ![image](https://github.com/user-attachments/assets/f9055ced-18e0-43e8-8492-5ad5bca9df70) |
**Summary**
Fixed the spacing between `Subscribe To Our Newsletter` and icons. Remove double border bottom from accordion.
- src/components/Accordion/_accordion.scss: Remove double border bottom from accordion
- src/patterns/Social/_social.scss: Fixed the spacing between `Subscribe To Our Newsletter` and icons
- verify that space between  `Subscribe To Our Newsletter` and …
> feat(social|accordion): L3-3723 fixed spacing for Footer

- src/components/Text/_text.scss
[L3-3572](https://phillipsauctions.atlassian.net/browse/L3-3572)
| ![image](https://github.com/user-attachments/assets/e71afcd6-306c-488a-8242-84bae4b7713c) | ![image](https://github.com/user-attachments/assets/c7c0c9e8-49f5-46f3-af3c-0c1b288bc5c1) |
**Summary**
lifted up superscript  in text component
- verify that superscript follows [figma ](https://www.figma.com/design/hxqgsE26wM7hII0WaUaDfF/RW---TIMED-Lot-Details-(PDP)?node-id=1-1305&node-type=instance&m=dev)design
**Evidence …
> feat(text): L3-3572 lifted up superscript 

- src/components/Drawer/Drawer.stories.tsx
- src/components/Dropdown/_dropdown.scss
- src/components/Input/_input.scss
- src/patterns/Subscribe/Subscribe.stories.tsx
- src/patterns/Subscribe/Subscribe.tsx
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-3829)
| ![image](https://github.com/user-attachments/assets/022189f3-f703-442b-a2e4-e08740146ae1) | ![image](https://github.com/user-attachments/assets/0a404c2b-1c78-40b2-98ef-171d6769bcba) |
**Summary**
Users would expect to be focused by default on the email input when the subscribe form opens, this change adds a property to be set to allow it.
- change(*.scss): fix input component focus states to match others (outline black)
- change(Subscribe): add autoFocus prop that focuses on the Input when set
- Popup the Drawer and Subscribe stories and verify that …
> feat(subscribe): L3-3829 add ability to autofocus the input

- src/components/Search/Search.tsx
- src/components/Search/SearchResults/SearchResults.tsx
- src/components/Search/SearchResults/_searchResults.scss
- src/components/Search/_search.scss
- src/components/Search/_searchButton.scss
- src/site-furniture/Header/_header.scss
[L3-3688](https://phillipsauctions.atlassian.net/browse/L3-3688)
**Summary**
Added user input highlight and fixed search expansion animation on mobile
New Components
[L3-3688]: https://phillipsauctions.atlassian.net/browse/L3-3688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(header): L3-3688 Highlight User Input In Search Results

- src/components/Accordion/Accordion.stories.tsx
- src/components/Accordion/AccordionItem.tsx
- src/components/Accordion/_accordion.scss
- src/components/Accordion/index.ts
- src/components/Accordion/types.ts
- src/components/Accordion/utils.ts
- src/components/Navigation/NavigationItemTrigger/NavigationItemTrigger.tsx
- src/patterns/LanguageSelector/LanguageSelector.tsx
- src/site-furniture/Footer/Footer.stories.tsx
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-3154)
| ![image](https://github.com/user-attachments/assets/08c385b7-8cb0-4bba-b894-5132d488237d) | ![image](https://github.com/user-attachments/assets/73df577c-9aa5-4c3d-af38-eb10e7104d7c) |
**Summary**
As I worked on the Lot Details accordion, I noticed that the default Accordion styles did not match the Figma and Footer and Header were having to override some styling to make them match, this fixes the default Accordion and AccordionItem styles.  I also made some typescript and prop model improvements while in there.
- change(AccordionItem): rename `variation` to `variant` to be consistent and …
> fix(accordion): L3-3154 lot details accordion styles do not match FIGMA

- src/components/Search/Search.tsx
- src/components/Search/SearchButton.tsx
[L3-1663](https://phillipsauctions.atlassian.net/browse/L3-1663)
| N/A | N/A |
**Summary**
Added onCancel callback to the Search component
- src/components/Search/Search.tsx: added onCancel callback
- src/components/Search/SearchButton.tsx: added onCancel callback
- verify that Header and Search components are working as usual
New Components
[L3-1663]: https://phillipsauctions.atlassian.net/browse/L3-1663?atlOrigin=eyJpIjoiNWR …
> feat(header): L3-1663 added onCancel callback

- package-lock.json
- package.json
- src/componentStyles.scss
- src/components/Carousel/Carousel.stories.tsx
- src/components/Carousel/Carousel.tsx
- src/components/Carousel/CarouselDots.tsx
- src/components/Carousel/CarouselItem.tsx
- src/components/Carousel/_carousel.scss
- src/components/Modal/Modal.tsx
- src/components/PinchZoom/PinchZoom.stories.tsx
- src/components/PinchZoom/PinchZoom.test.tsx
- src/components/PinchZoom/PinchZoom.tsx
- src/components/PinchZoom/_pinchZoom.scss
- src/components/PinchZoom/index.ts
- src/index.ts
- src/scss/_utils.scss
- vite.config.ts
[L3-3145](https://phillipsauctions.atlassian.net/browse/L3-3145)
https://github.com/user-attachments/assets/76198f78-376d-4d8b-8fa7-02b4ee50af48
**Summary**
A pinch zoom component in seldon
Nicely accompanied by the carousel component to form a pinch zoom carousel
To be accompanied by a remix PR shortly
- New Pinch Zoom Component
- Stories demonstrating pinch zoom component when combined with both carousel and modal
- Tiny test suite (need better way to simulate wheel in / out, but otherwise not too much to test?)
- Small updates to carousel & modal components to allow more customization
**Regression …
> feat(lotdetails): L3-3145 pinch zoom component in seldon

- src/components/Search/Search.tsx
[L3-1663](https://phillipsauctions.atlassian.net/browse/L3-1663)
| N/A | N/A |
**Summary**
Changed the order of form reset to fix search result disappearing 
- src/components/Search/Search.tsx: changed the order of reset
- no way to verify on Seldon's side
New Components
[L3-1663]: https://phillipsauctions.atlassian.net/browse/L3-1663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> feat(search): L3-1663 fixed closing functionality

- src/patterns/DetailList/index.ts
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/TICKET-ID)
**Summary**
Just exporting this enum so it can be used as a prop on the remix side
New Components
> chore(DetailList): L3-3155 export DetailListAlignment enum

- src/components/Carousel/CarouselDots.tsx
[L3-3145](https://phillipsauctions.atlassian.net/browse/L3-3145)
**Summary**
Don't use index for key on CarouselDots
New Components
[L3-3145]: https://phillipsauctions.atlassian.net/browse/L3-3145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(lotdetails): L3-3145 dont use index key on carousel dots

- src/components/Detail/Detail.stories.tsx
- src/components/Detail/Detail.tsx
- src/patterns/DetailList/DetailList.stories.tsx
- src/patterns/DetailList/DetailList.test.tsx
- src/patterns/DetailList/DetailList.tsx
- src/patterns/DetailList/index.ts
[L3-4057](https://phillipsauctions.atlassian.net/browse/L3-4057)
| N/A | N/A |
**Summary**
Updated `DetailList` and `Detail`
- src/components/Detail/Detail.tsx: updated type of `value` and `label` to take not only `sting` but `ReactNode` as a child, added optional and default props
- src/patterns/DetailList/DetailList.tsx: added single element support, removed `undefined` class name, removed generic `index` key, added optional and default props
- src/patterns/DetailList/index.ts: exported type enum
- verify that you can add one element to `DetailList`
- verify that `Detail` class name is not undefined in DOM
- verify that …
> feat(detail): L3-4057 detail list improvement

- .storybook/CustomStoryWrapper.tsx
- src/componentStyles.scss
- src/index.ts
- src/providers/SeldonProvider/SeldonProvider.stories.tsx
- src/providers/SeldonProvider/SeldonProvider.test.tsx
- src/providers/SeldonProvider/SeldonProvider.tsx
- src/providers/SeldonProvider/_seldonProvider.scss
- src/scss/_reset.scss
[L3-4061](https://phillipsauctions.atlassian.net/browse/L3-4061)
| ![image](https://github.com/user-attachments/assets/b74be78c-d1db-49c9-9a33-6301c8bc974d) | ![image](https://github.com/user-attachments/assets/89bd621a-87e6-45db-b0c9-68639a86db5e) |
**Summary**
Searchresult highlighting using the <strong> tag wasn't working in Remix because our font variation settings were overriding it.  It worked in storybook because we applied a <strong> font-weight override in the storybook specific styling
- change(componentStyles): add seldonProvider styles
- change(SeldonProvider): move to a subdirectory
- add(seldonProvider.scss):  move the global resets to this scoped …
> fix(searchresults): L3-4061 matching text was not highlighting

- src/providers/SeldonProvider/_seldonProvider.scss
[L3-4079](https://phillipsauctions.atlassian.net/browse/L3-4079)
| <img width="784" alt="image" src="https://github.com/user-attachments/assets/7a51020b-4319-492f-82ee-12056d49c353"> | <img width="842" alt="image" src="https://github.com/user-attachments/assets/4644d962-bfaf-4ff5-98b9-b4ba7d926b12"> |
**Summary**
Overly aggressive margin reset in our reset caused a bunch of issues downstream, one of which being the search layout on mobile.
- change(seldonProvider): remove the global margin reset and instead specifically target it to our text elements
- Validate search function looks correct now in header story on Mobile …
> fix(provider): L3-4079 global reset to margins was too aggressive

- src/components/Accordion/_accordion.scss
- src/components/TextSymbol/_textSymbol.scss
- src/patterns/DetailList/DetailList.tsx
- src/patterns/DetailList/_detailList.scss
- src/providers/SeldonProvider/_seldonProvider.scss
[L3-3155](https://phillipsauctions.atlassian.net/browse/L3-3155)
| <img width="582" alt="image" src="https://github.com/user-attachments/assets/cda43a25-5c54-4f79-b640-9bbe4cad5717"> | <img width="550" alt="image" src="https://github.com/user-attachments/assets/5171b41f-f309-402b-8b65-c3ad54c6506e"> |
**Summary**
While testing the multiple estimates feature in remix, I noticed a few style fixes that needed to be made to "Accordions", textSymbol, and DetailList.  I also found that if I try and pass undefined as one of the children to DetailList (which is a common React pattern for optional content), it would render an empty detail div.
- change(accordion): need to …
> fix(detaillist): L3-3155 style fix and undefined child fix

- src/componentStyles.scss
- src/components/Carousel/CarouselDots.tsx
- src/components/Carousel/_carousel.scss
- src/components/PinchZoom/PinchZoom.stories.tsx
- src/components/SeldonImage/SeldonImage.stories.tsx
- src/components/SeldonImage/SeldonImage.test.tsx
- src/components/SeldonImage/SeldonImage.tsx
- src/components/SeldonImage/_seldonImage.scss
- src/components/SeldonImage/index.ts
- src/index.ts
[L3-1466](https://phillipsauctions.atlassian.net/browse/L3-1466)
**Summary**
Seldon image component
Support different aspect ratios & fill modes
With optional blur background
TBD loading & error states
- SeldonImage component, stories, and tests
New Components
[L3-1466]: https://phillipsauctions.atlassian.net/browse/L3-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
> feat(imagecomponent): L3-1466 seldon image component

- src/patterns/DetailList/_detailList.scss
[L3-4081](https://phillipsauctions.atlassian.net/browse/L3-4081)
| <img width="386" alt="image" src="https://github.com/user-attachments/assets/b19239dc-7768-4983-af3b-08c073aaf906"> | <img width="373" alt="image" src="https://github.com/user-attachments/assets/b53b5ca3-a2dd-41ca-bd80-528274672c1e"> |
**Summary**
Small change to remove extra padding that was found while using the details list in the estimate panel in Remix
- change(detailList): remove the gap and margins
- Confirm the details list story doesn't have extra padding between the items.
- (Optional) Add verification steps to make sure this …
> fix(detaillist): L3-4081 style fix to remove extra padding at bottom of detail items

- src/patterns/DetailList/DetailList.stories.tsx
- src/patterns/DetailList/DetailList.tsx
- src/patterns/DetailList/_detailList.scss
[L3-3296](https://phillipsauctions.atlassian.net/browse/L3-3296)
Updated story:
**Summary**
Made some adjustments to the styles of the DetailList and updated the story to display all 4 possible variants
New Components
[L3-3296]: https://phillipsauctions.atlassian.net/browse/L3-3296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
> fix(DetailList): L3-3296 DetailList improvements

- src/components/Pagination/Pagination.stories.tsx
- src/components/Pagination/_pagination.scss
- src/scss/_reset.scss
[L3-4096](https://phillipsauctions.atlassian.net/browse/L3-4096)
| <img width="534" alt="Pasted Graphic 1" src="https://github.com/user-attachments/assets/81a1c166-b42d-4c1f-8a06-4f20cf4d2c12"> | <img width="573" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/16a32d33-f431-4958-a7b7-173ca95432ea"> |
**Summary**
Changes Pagination style for the buttons to match the Figma
- change(Pagination.stories): make more like the real figma options
- change(pagination.scss): increase arrow size
- Compare the Pagination Story from localhost to the Figma and to the deployed phillips seldon
- …
> fix(pagination): L3-4096 arrow buttons were too small

- src/components/Accordion/AccordionItem.tsx
- src/components/Accordion/_accordion.scss
[L3-4103](https://phillipsauctions.atlassian.net/browse/L3-4103)
| <img width="1445" alt="image" src="https://github.com/user-attachments/assets/69e6ba4c-8d36-4925-85d9-56b3d5f61093"> | <img width="1434" alt="image" src="https://github.com/user-attachments/assets/3c669fc4-66c4-4881-83f4-678feafc2f88"> |
**Summary**
Accordion content for small items was not using a top spacing (large was)
- change(accordionitem): apply the spacing to both large and small accordion content
- Verify the accordion story
- I pulled the seldon version into Remix and checked our existing accordionitems and adjusted in my next …
> fix(accordion): L3-4103 fix spacing on accordion content

- package-lock.json
- src/components/Navigation/NavigationItemTrigger/_navigationItemTrigger.scss
- src/site-furniture/Header/Header.stories.tsx
- src/site-furniture/Header/Header.tsx
[L3-4181](https://phillipsauctions.atlassian.net/browse/L3-4181)
| ![image](https://github.com/user-attachments/assets/35144d86-d51c-44f1-93ec-6f86a166ea2d) | ![image](https://github.com/user-attachments/assets/bcf465cb-0224-4417-b55d-f1d4e00f0b07) |
**Summary**
Added scroll to the auctions links
- src/components/Navigation/NavigationItemTrigger/_navigationItemTrigger.scss: added scroll to the auction container
- src/site-furniture/Header/Header.stories.tsx: added more auctions to show scroll
- src/site-furniture/Header/Header.tsx: added prop which will help to get i18 link on Phillips-Public side
- resize height of …
> feat(navigationItemTrigger): L3-4181 added scroll on dropdown

- src/components/TextSymbol/_textSymbol.scss
[L3-4109](https://phillipsauctions.atlassian.net/browse/L3-4109)
Chrome:
| ![image](https://github.com/user-attachments/assets/189c45f0-b540-4b54-b07d-b444b97089dd) | ![image](https://github.com/user-attachments/assets/53840c55-b044-4921-a34d-db4f1b959323) |
iOS Safari
| ![image](https://github.com/user-attachments/assets/7c9f3626-a9e7-4de1-bf43-975db7452419) | ![image](https://github.com/user-attachments/assets/531f4573-bc3b-4ef6-8335-716ddc99ca23) |
**Summary**
Changes the font-family so that the symbol for spade matches the size of the other symbols
- change(textSymbol)
- Verify …
> fix(textSymbol): L3-4109 reduce size of estimate symbol

- src/components/Pagination/_pagination.scss
[L3-4167](https://phillipsauctions.atlassian.net/browse/L3-4167)
| ![image](https://github.com/user-attachments/assets/c6f77280-a108-4ede-a600-20f452a30b06) | ![image](https://github.com/user-attachments/assets/a35b92b0-70e5-4244-bc47-4cbe845fcdfd) |
**Summary**
For some reason `text-align: center` doesn't work for Selects on iOS safari so I have to use `text-align-last`. (Found through Google)
- change(pagination.scss): add the `text-align-last: center` to get it to work on iOS Safari
- Verify on iOS simulator in the Pagination story on Seldon
- Check the other browsers
- On …
> fix(pagination): L3-4167 center align select on iOS

- src/components/Accordion/_accordion.scss
- src/components/Navigation/NavigationList/_navigationList.scss
- src/components/Text/types.ts
- src/components/Text/utils.ts
- src/design/type-tokens/_text-showcase.scss
- src/patterns/HeroBanner/HeroBanner.tsx
- src/patterns/HeroBanner/_heroBanner.scss
- src/scss/_type.scss
- src/scss/_vars.scss
- src/site-furniture/Header/Header.test.tsx
- src/site-furniture/Header/Header.tsx
- src/site-furniture/Header/_header.scss
[L3-4227](https://phillipsauctions.atlassian.net/browse/L3-4227)
| ![image](https://github.com/user-attachments/assets/c35882fd-9700-403a-a99e-b130aa822d69) | ![image](https://github.com/user-attachments/assets/be157eee-068b-44c9-bdae-f8553f310eda) |
[L3-4230](https://phillipsauctions.atlassian.net/browse/L3-4230)
| ![image](https://github.com/user-attachments/assets/644fdd06-154c-4525-9ea6-7042ad17b283) | ![image](https://github.com/user-attachments/assets/c4e0e2d7-115a-480f-a81e-9aa86136c242) |
[L3-4193](https://phillipsauctions.atlassian.net/browse/L3-4193)
| ![image](https://github.com/user-attachments/assets/aefd4c3a-0483-48e5-b20b-3a394f06bf77) | …
> feat(header): L3-4227 header changes

- src/components/Pagination/_pagination.scss
- src/index.ts
[L3-3158](https://phillipsauctions.atlassian.net/browse/L3-3158)
Notice that the pagination has less whitespace between it and the Lot Timer in the second screenshot
| ![image](https://github.com/user-attachments/assets/40775182-c288-420d-bcda-a33bf96d8f61) | ![image](https://github.com/user-attachments/assets/b2c5e049-db39-410e-a2fb-9d7fbda964a4) |
**Summary**
Fix to the reduce the height of the pagination controls on mobile to match the Figma.  (This was found when I tried to position the Lot Timer right underneath it).  I also would like to reuse the SeldonProvider fresnel context for our breakpoints directly within remix.
- change(index): export the fresnel …
> fix(pagination): L3-3158 update style so it is shorter on mobile

- src/components/Accordion/AccordionItem.tsx
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.test.tsx
- src/components/Button/Button.tsx
- src/components/Button/_button.scss
- src/components/Button/types.ts
- src/components/Input/Input.stories.tsx
[L3-3327](https://phillipsauctions.atlassian.net/browse/L3-3327)
**Summary**
Adding a link variant to the button (make it accept an href too), add forward ref to accordion
In support of condition report on remix
- href and link variant passed to button
- ref passed to accordion item
- story for controlled input
New Components
[L3-3327]: https://phillipsauctions.atlassian.net/browse/L3-3327?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
> chore(lotdetails): L3-3327 button and accordion changes for condition report

- src/components/Button/Button.tsx
[L3-3327](https://phillipsauctions.atlassian.net/browse/L3-3327)
**Summary**
Forcing a republish for changes in https://github.com/PhillipsAuctionHouse/seldon/pull/397
New Components
[L3-3327]: https://phillipsauctions.atlassian.net/browse/L3-3327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(lotdetails): L3-3327 trigger build for button & accordion updates

- src/site-furniture/Header/_header.scss
[L3-4294](https://phillipsauctions.atlassian.net/browse/L3-4294)
[L3-4295](https://phillipsauctions.atlassian.net/browse/L3-4295)
|![Screenshot 2024-10-24 133259](https://github.com/user-attachments/assets/07af72f0-8b47-4242-bdad-a896e0d66c12) | ![Screenshot 2024-10-24 133047](https://github.com/user-attachments/assets/aa475ffe-3fab-470e-ab6d-e770c672d638)|
**Summary**
Fixes were made to spacing below Search and scroll fixes for device menus blocking language selection
- CSS changes for padding and switch from vh to dvh screen size measurement
- View storybook Header story on mobile device and scroll to bottom on mobile …
> fix(header): L3-4294 Dvh Fix for Mobile Scroll Issue Nav Spacing Fix

- src/components/Link/_link.scss
- src/patterns/UserManagement/_userManagement.scss
- src/scss/_type.scss
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-4294)
| ![image](https://github.com/user-attachments/assets/6411f392-1aa1-43b5-b26b-7104f9ef4916) | ![image](https://github.com/user-attachments/assets/15a46b08-3ee1-4ed3-b800-75a1d996cc8f) |
**Summary**
Fixed the link underline
- src/scss/_type.scss: updated the underline mixin
- test that links underline looks correct
New Components
> feat(header): L3-4294 links underline fix

- src/components/SeldonImage/SeldonImage.stories.tsx
- src/components/SeldonImage/SeldonImage.test.tsx
- src/components/SeldonImage/SeldonImage.tsx
[L3-4323](https://phillipsauctions.atlassian.net/browse/L3-4323)
**Summary**
Fix image error states for SSR page load
- do image loading logic in useEffect instead of relying on DOM events (dont fire server side)
New Components
[L3-4323]: https://phillipsauctions.atlassian.net/browse/L3-4323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(lotdetails): L3-4323 image carousel SSR error state

- src/components/Accordion/Accordion.stories.tsx
- src/components/Accordion/AccordionItem.test.tsx
- src/components/Accordion/AccordionItem.tsx
- src/components/Accordion/_accordion.scss
[L3-3296](https://phillipsauctions.atlassian.net/browse/L3-3296)
| ![image](https://github.com/user-attachments/assets/839ee10e-48cb-44ba-baff-143ea773bab1)
| ![image](https://github.com/user-attachments/assets/6aac6a62-abd8-4e3b-a75a-6faa2b323dd0)|
**Summary**
Found an issue when using Accordion in Lot Details where passing a custom className to `AccordionItem` would break it's styles.  I also noticed for large accordionitem content it might be good to allow overrides of the default 250ms transition.
- change(AccordionItem): make custom `className` additive rather than allowing it to override the base `AccordionItem` styles.  Add new optional prop …
> feat(accordion): L3-3296 support custom transition time

- src/components/Accordion/AccordionItem.tsx
- src/components/Accordion/types.ts
- src/components/Input/_input.scss
[L3-3327](https://phillipsauctions.atlassian.net/browse/L3-3327)
**Before**
**After**
**Summary**
Match invalid email styles to compendium
- keep invalid text black, increase font weight of input text, red outline on focused invalid input
- add onOpen/onClose props to accordion item
New Components
[L3-3327]: https://phillipsauctions.atlassian.net/browse/L3-3327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
> fix(lotdetails): L3-3327 minor changes to input and accordion to match compendium

- src/components/Tabs/TabTrigger.tsx
- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/Tabs.test.tsx
- src/components/Tabs/TabsContainer.tsx
[L3-2395](https://phillipsauctions.atlassian.net/browse/TICKET-ID)
**Summary**
While the Tabs component supported an `defaultValue` prop (for uncontrolled tabs with internal state), it didn't support the `value` prop for fully controlled tabs where the parent component passes in the state externally.  (This is useful for doing things like updating the URL when we switch tabs, which allows bookmarking of a page with a particular tab selected.)
- change(TabTrigger): rename `onTabClick` to `onClick` to be consistent with other buttons
- change(TabsContainer): add value prop and pass through all the other props to `TabsPrimitive.Root` in case we want to support another capability of Radix
**Acceptance Test (how to verify …
> feat(tabs): L3-2396 tabs add controlled state

- src/components/Search/Search.tsx
[L3-4328](https://phillipsauctions.atlassian.net/browse/L3-4328)
| N/A | N/A |
**Summary**
Fixing search results closing functionality
- src/components/Search/Search.tsx: added on close handlers
- there is no way to verify these changes on Seldon, PP specific change only
New Components
[L3-4328]: https://phillipsauctions.atlassian.net/browse/L3-4328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
> feat(search): L3-4328 onKeyDown fix

- src/components/ContentPeek/ContentPeek.stories.tsx
- src/components/ContentPeek/ContentPeek.tsx
- src/components/ContentPeek/utils.ts
[L3-4299](https://phillipsauctions.atlassian.net/browse/L3-4299)
Before:
| --- | --- |
|<video src="https://github.com/user-attachments/assets/32cfcabc-2d2c-4e4b-b08b-6e727ec761f0">|<video src="https://github.com/user-attachments/assets/1448bed9-96b9-4dfd-a216-2c38a5300d3c">|
**Summary**
The requirement for L3-4299 specifies that any content under 38rem should be shown without Peek controls, but any content above 38 rem should show the Peek, with the peeked content maxed at 30rem. With the current component this isn't psosible, so I added a new prop: `minHeightThreshold`. By default, it will be the same as the `maxHeight`, so it will work the same as it does today if `minHeightThreshold` isn't specified, but it can be passed separately to …
> feat(ContentPeek): L3-4299 - add new prop for specifying the minHeightThreshold for showing Peek controls

- src/components/Countdown/Countdown.test.tsx
- src/components/Countdown/Countdown.tsx
- src/components/Row/Row.tsx
- src/patterns/BidSnapshot/BidSnapshot.stories.tsx
- src/patterns/BidSnapshot/BidSnapshot.test.tsx
- src/patterns/BidSnapshot/BidSnapshot.tsx
- src/patterns/BidSnapshot/_bidSnapshot.scss
- src/patterns/BidSnapshot/index.ts
- src/patterns/ObjectTile/ObjectTile.stories.tsx
- src/patterns/ObjectTile/ObjectTile.tsx
[L3-4346](https://phillipsauctions.atlassian.net/browse/L3-4346)
**Summary**
Made changes to Object tile to deal with data coming from API
- removed default value for countdown string `src/components/Countdown/Countdown.tsx`
- removed the test checking for default `src/components/Countdown/Countdown.test.tsx`
- Change typing of Row children - `src/components/Row/Row.tsx`
- Updated BidSnapshot stories to account for changes - `src/patterns/BidSnapshot/BidSnapshot.stories.tsx`
- Updated test to account for changes - `src/patterns/BidSnapshot/BidSnapshot.stories.tsx`
- Updated BidSnapshot to better serve use case - `src/patterns/BidSnapshot/BidSnapshot.tsx`
- Changed styles - `src/patterns/BidSnapshot/_bidSnapshot.scss` …
> fix(objecttile): L3-4346 - object tiles fix

- src/components/Select/Select.tsx
[L3-3818](https://phillipsauctions.atlassian.net/browse/L3-3818)
| N/A | N/A |
**Summary**
Fixed `className` usage for Select component 
- replaced `className`
New Components
[L3-3818]: https://phillipsauctions.atlassian.net/browse/L3-3818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(select): L3-3818 className fix

- src/assets/icon-green-circle.svg
- src/assets/icon-red-circle.svg
- src/assets/icons.ts
- src/patterns/BidSnapshot/BidMessage.test.tsx
- src/patterns/BidSnapshot/BidMessage.tsx
- src/patterns/BidSnapshot/BidSnapshot.stories.tsx
- src/patterns/BidSnapshot/BidSnapshot.test.tsx
- src/patterns/BidSnapshot/BidSnapshot.tsx
- src/patterns/BidSnapshot/_bidSnapshot.scss
- src/patterns/BidSnapshot/index.ts
- src/patterns/BidSnapshot/types.ts
- src/patterns/ObjectTile/ObjectTile.stories.tsx
[L3-4378](https://phillipsauctions.atlassian.net/browse/L3-4378)
| ![image](https://github.com/user-attachments/assets/0bb423a9-33b7-4390-a298-0274483dce57) | ![image](https://github.com/user-attachments/assets/5034cb3d-5fa8-4604-977e-857dc6dbc865) |
**Summary**
The `activeBid` prop was pretty confusing as it was "your" currently active, non-max bid.  Instead taking a bidStatus prop is easier to understand and better aligns with the way our Remix components work
- change(BidSnapshot): change `activeBid` to `bidStatus` and create reusable enum.  Only hide the `bidStatus` message not any other children.
- change(BidMessage): use icon that matches Figma instead of …
> feat(bidsnapshot)!: L3-4378 change prop model to support multiple bid statuses in the future

- src/patterns/Social/_social.scss
[L3-4461](https://phillipsauctions.atlassian.net/browse/L3-4461)
| ![image](https://github.com/user-attachments/assets/0a6f69c3-510a-4b5f-b14e-0b95c0218a1d) | ![image](https://github.com/user-attachments/assets/e011cd4f-d49e-4c69-b115-844cec618e33) |
**Summary**
Update title case to says Subscribe To Our Newsletter
Open Screenshot 2024-11-04 at 11.17.21 AM.png
Screenshot 2024-11-04 at 11.17.21 AM.png
**Evidence of …
> fix(footer): L3-4461 Update casing on newsletter subscription

- package-lock.json
- package.json
- src/components/Carousel/Carousel.stories.tsx
- src/components/Carousel/CarouselDot.tsx
- src/components/Carousel/CarouselDots.tsx
- src/components/Carousel/_carousel.scss
- src/components/PinchZoom/PinchZoom.stories.tsx
- src/components/PinchZoom/PinchZoom.tsx
[L3-4045](https://phillipsauctions.atlassian.net/browse/L3-4045)
**Dot Overflow**
https://github.com/user-attachments/assets/b0f74550-9de5-4cc5-b05c-733c3fcf4a10
**Carousel when item is zoomed and at edge**
https://github.com/user-attachments/assets/d0be4a68-359d-445b-bbae-b4668af9d0b6
**Summary**
Add carousel dots overflow behavior
https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium%3A-Tokens%2C-Components-%26-Patterns?m=auto&node-id=15894-140133&focus-id=15894-140065
And the ability to pan to the next carousel item when zoomed in and at the edge of an item
- Use intersection observer in CarouselDots & CarouselDot to track dot visibility and shrink/unshrink
- Add tracking to the …
> feat(carousel): L3-4045 carousel overflow and zoom/pan behavior

- src/patterns/SaleHeaderBanner/_saleHeaderBanner.scss
[L3-4648](https://phillipsauctions.atlassian.net/browse/L3-4648)
| ![image](https://github.com/user-attachments/assets/1abe1ab8-61f5-4267-a0ab-88d5da9f37c9) | ![image](https://github.com/user-attachments/assets/7c582c45-44ae-448b-8398-94fe521c1e49) |
**Summary**
Just a couple of small style fixes for the Countdown timer when rendered in the SaleHeaderBanner
**Things to …
> fix(SaleHeaderBanner): L3-4648 center countdown component in header banner

- src/patterns/ObjectTile/ObjectTile.tsx
[L3-4753](https://phillipsauctions.atlassian.net/browse/L3-4753)
**Summary**
Pass srcset and sizes to object tile 
- Add srcset and sizes prop to object tile
New Components
[L3-4753]: https://phillipsauctions.atlassian.net/browse/L3-4753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(objecttile): L3-4753 accept srcset & sizes from object tile

- src/components/SeldonImage/SeldonImage.test.tsx
- src/components/SeldonImage/SeldonImage.tsx
- src/components/SeldonImage/_seldonImage.scss
- src/patterns/ObjectTile/ObjectTile.stories.tsx
- src/patterns/ObjectTile/ObjectTile.tsx
- src/patterns/SaleHeaderBanner/SaleHeaderBanner.tsx
[L3-4753](https://phillipsauctions.atlassian.net/browse/L3-4753)
**Summary**
More image optimization logic in SeldonImage and memoizing object tile
- More image opt logic in SeldonImage
- Memoize object tile
- SeldonImage and ObjectTile still work
New Components
[L3-4753]: https://phillipsauctions.atlassian.net/browse/L3-4753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(seldonimage): L3-4753 more opts

- src/index.ts
[L3-5032](https://phillipsauctions.atlassian.net/browse/L3-5032)
| N/A | N/A |
**Summary**
Added import for Tag component
- src/index.ts: added import for Tag component
New Components
[L3-5032]: https://phillipsauctions.atlassian.net/browse/L3-5032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(Tags): L3-5032 added import for Tags

- src/patterns/BidSnapshot/BidSnapshot.stories.tsx
- src/patterns/BidSnapshot/BidSnapshot.test.tsx
- src/patterns/BidSnapshot/BidSnapshot.tsx
- src/patterns/ObjectTile/ObjectTile.stories.tsx
[L3-4767](https://phillipsauctions.atlassian.net/browse/L3-4767)
**Summary**
Our Lot Tiles were showing the Close Timer even if the Lots didn't close for 300 days :). According to design we should only show the close timer on the Sale Browse tab when the sale is within 1 hour of starting its close.
- change(BidSnapshot): Improve the timer logic to only show when the sale is near or has started closing...
- View the BidSnapshot story.  
- Adjust the Sale Close Date to be out farther in the future than 1 hour, the timer should not show
- Adjust the Sale Close Date to be in the past.  The Timer should show
- (Optional) Add verification steps to make sure …
> fix(bidsnapshot): L3-4767 lot timer should only show if the sale starts closing in the next 60 minutes

- src/components/GridItem/_gridItem.scss
- src/components/Text/Text.stories.tsx
- src/components/Text/Text.tsx
- src/components/Text/_text.scss
- src/components/Text/types.ts
- src/components/Text/utils.ts
[L3-3958(https://phillipsauctions.atlassian.net/browse/L3-3958)
**Summary**
Don't default center the text in a grid item, give text an alignment option
- Remove text-align in centered grid items (child text should handle that)
- Add text alignment option to Text
- Text & Grid should function as expected
New Components
> feat(text): L3-3958 grid centering and text alignment

- src/patterns/ObjectTile/_objectTile.scss
[L3-4682](https://phillipsauctions.atlassian.net/browse/L3-4682)
| ![image](https://github.com/user-attachments/assets/9120c61a-4805-4a5c-8872-59d997cbc7e5) | ![image](https://github.com/user-attachments/assets/222759ab-102d-46d2-b266-1225b947a61f) |
**Summary**
Aligns the ObjectTile with the Figmas, specifically to italicize model  and reference number (usually used for Watches)
- change(objectTile.scss): italicize model and ref number
- View the Object Tile story
- Post logs, screenshots, …
> fix(objecttile): L3-4682 italicize model and referenceNumber

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.test.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/_dropdown.scss
- src/patterns/LanguageSelector/LanguageSelector.test.tsx
- src/patterns/LanguageSelector/LanguageSelector.tsx
- src/patterns/UserManagement/UserManagement.stories.tsx
- src/patterns/UserManagement/UserManagement.test.tsx
- src/patterns/UserManagement/UserManagement.tsx
- src/patterns/UserManagement/_userManagement.scss
- src/site-furniture/Header/Header.tsx
[L3-4289](https://phillipsauctions.atlassian.net/browse/L3-4289)
**Summary**
This is specifically in the Header where we want to disable the LanguageSelector and UserManagement before javascript hydrates in Remix.  This will allow our Playwright tests to wait until these buttons are actually actionable before clicking them.
- change(Dropdown): add disabled prop
- change(dropdown.scss): change color when disabled and mouse events
- change(LanguageSelector): allow disabling
- change(Header): allow disabling of Language Selector
- change(UserManagement): allow disabling
- Go to the Header, LanguageSelector, and Dropdown stories and set `disabled=true` and …
> feat(header): L3-4289 support disabling top row of header

- src/patterns/SaleHeaderBanner/SaleHeaderBanner.stories.tsx
- src/patterns/SaleHeaderBanner/SaleHeaderBanner.test.tsx
- src/patterns/SaleHeaderBanner/SaleHeaderBanner.tsx
[L3-4298](https://phillipsauctions.atlassian.net/browse/L3-4298)
| ![image](https://github.com/user-attachments/assets/1c2c2788-bce4-42b9-8c1d-d807009d71c8) | ![image](https://github.com/user-attachments/assets/fc13f623-7a67-49ab-9227-89b24cc59638) |
**Summary**
The Countdown timer related fields in the SaleHeaderBanner were not translatable, this adds that capability
Key changes include:
* Added `countdownTimerLabel` and `countdownFormatDuration` properties to `SaleHeaderBannerProps` to allow customization of the countdown timer label and duration format.
* Updated the `SaleHeaderBanner` component to use the new countdown properties when rendering the countdown …
> fix(saleheaderbanner): L3-4298 support translations for the countdown component

- src/patterns/SaleHeaderBanner/_saleHeaderBanner.scss
[L3-5179](https://phillipsauctions.atlassian.net/browse/L3-5179)
| ![Screenshot 2025-01-27 124856](https://github.com/user-attachments/assets/e3b02649-0a99-47b7-8d45-97cc1fedf876) | ![Screenshot 2025-01-27 130043](https://github.com/user-attachments/assets/ee645555-213f-4747-a3ae-6009e9815475) |
**Figma link**
[Figma Link](https://www.figma.com/design/OvBXAq48blO1r4qYbeBPjW/RW---Sale-Page-(PLP)?node-id=274-227833&m=dev)
**Summary**
This PR fixes the spacing issue with the footer elements of the sale header banner.
- * [`src/patterns/SaleHeaderBanner/_saleHeaderBanner.scss`](diffhunk://#diff-29768014c7e5e596faebd0d6d885bae1b53f57174560bd072712cfda9a558fd9L66-R71): …
> fix(SaleHeaderBanner): L3-5179 fix spacing of sale header banner footer elements

- src/assets/checkmark.svg
- src/assets/icons.ts
[L3-3337](https://phillipsauctions.atlassian.net/browse/L3-3337)
**Figma link**
[Figma Link](https://www.figma.com/design/hxqgsE26wM7hII0WaUaDfF/RW---TIMED-Lot-Details-(PDP)?m=auto&node-id=5919-14123)
**Summary**
Exporting checkmark icon for bid modal
- add checkmark svg and export
New Components
[L3-3337]: https://phillipsauctions.atlassian.net/browse/L3-3337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> feat(icons): L3-3337 checkmark icon

- src/components/Countdown/_countdown.scss
[L3-5327](https://phillipsauctions.atlassian.net/browse/L3-5327)
| ![Screenshot 2025-02-06 153734](https://github.com/user-attachments/assets/097bdac7-ed95-4aa9-ae83-84ec8c39c66b) | ![Screenshot 2025-02-06 155908](https://github.com/user-attachments/assets/2e299f89-1820-459e-8f36-22323e380116) |
**Figma link**
[Figma Link](https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium%3A-Tokens%2C-Components-%26-Patterns?node-id=10225-13282&m=dev)
**Summary**
Tweaks some styles to ensure the timer fits better on the Lot page
Styling improvements:
* Modified the padding of the Countdown component to only apply padding to the bottom (`padding-bottom: …
> fix(Countdown): L3-5327 countdown issues

- src/components/Modal/_modal.scss
- src/patterns/BidSnapshot/BidSnapshot.test.tsx
- src/patterns/BidSnapshot/BidSnapshot.tsx
[L3-4833](https://phillipsauctions.atlassian.net/browse/L3-4833)
| ----- | ----- |
| <img width="367" alt="Screenshot 2025-02-06 at 6 12 35 PM" src="https://github.com/user-attachments/assets/51f626c1-832b-4ddf-95a1-5f41288d0398" /> | <img width="367" alt="Screenshot 2025-02-06 at 6 12 19 PM" src="https://github.com/user-attachments/assets/8db77e9b-9909-4a6a-8422-42b2649452a8" /> |
**Figma link**
[Figma Link](https://www.figma.com/design/OvBXAq48blO1r4qYbeBPjW/RW---Sale-Page-(PLP)?node-id=2617-163688&m=devK)
**Summary**
Only show "Won For" text when you have won
- Additions, Changes, and Removals. (You can use [GitHub Copilot PR …
> fix(bidsnapshot): L3-4833 only show won for text when auction is won

- src/components/Countdown/Countdown.test.tsx
- src/components/Countdown/Countdown.tsx
[L3-4833](https://phillipsauctions.atlassian.net/browse/L3-4833)
https://github.com/user-attachments/assets/f2ca7f9a-d8a1-48f3-8ba4-0e3bfd7aeb40
**Figma link**
**Summary**
Keep countdown rendered after it hits zero
- Countdown.tsx: default times to 0 if negative, show timer if it is before the end time on initial render
New Components
[L3-4833]: …
> feat(countdown): L3-4833 keep countdown on 00s when it closes

- src/componentStyles.scss
- src/components/Article/Article.stories.tsx
- src/components/Article/Article.test.tsx
- src/components/Article/Article.tsx
- src/components/Article/_article.scss
- src/components/Article/index.ts
- src/index.ts
[L3-5116](https://phillipsauctions.atlassian.net/browse/L3-5116)
| N/A | <img width="994" alt="Screenshot 2025-02-11 at 6 31 15 PM" src="https://github.com/user-attachments/assets/20490bab-3f2b-400d-b384-ec86fb281f40" /> |
**Figma link**
[Figma Link](https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium%3A-Tokens%2C-Components-%26-Patterns?node-id=20705-20412&m=dev)
**Summary**
Added Article component to Seldon
- src/components/Article/Article.stories.tsx: added default arguments
- src/components/Article/Article.tsx: added new component
- src/components/Article/_article.scss: added styles
- mobile version …
> feat(Article): L3-5116 added Article component

- src/components/Tags/Tags.stories.tsx
- src/components/Tags/Tags.test.tsx
- src/components/Tags/Tags.tsx
- src/components/Tags/_tags.scss
[L3-5077](https://phillipsauctions.atlassian.net/browse/TICKET-ID)
***Hover State***
| ![image](https://github.com/user-attachments/assets/6cd1de49-384c-4712-8edb-4cf9aa40319b) | ![image](https://github.com/user-attachments/assets/0e012365-aa10-47e6-a99a-cd1cadc6f8d1) |
***Focus States***
| ![image](https://github.com/user-attachments/assets/1cba73d2-de4d-4a80-af7d-50a1136b724b) | ![image](https://github.com/user-attachments/assets/dcfca39e-10d5-4639-a183-2bf843ce3acb) |
| ![image](https://github.com/user-attachments/assets/5083a132-3730-4cd8-8947-34e06f95e0b0) | ![image](https://github.com/user-attachments/assets/1f7fd631-942e-4f17-b015-b7490f9ee07b) |
**Figma link**
[Figma …
> fix(tags): L3-5077 update tag click behavior and styles for focus and hover state

- src/patterns/ObjectTile/_objectTile.scss
[L3-5242](https://phillipsauctions.atlassian.net/browse/L3-5242)
| ![image](https://github.com/user-attachments/assets/9b5d1a0f-9341-49cb-9662-4510bc280d4f) | ![image](https://github.com/user-attachments/assets/46e9adc4-7200-4fc4-afc3-34180a07658a) |
**Figma link**
[Figma Link](https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium%3A-Tokens%2C-Components-%26-Patterns?node-id=10914-34792&p=f&m=dev)
**Summary**
Truncated the title after 1 line. 
This pull request includes a small change to the `src/patterns/ObjectTile/_objectTile.scss` file. The change modifies the `-webkit-line-clamp` property from `2` to `1` for the `&__title` class.
**Acceptance …
> feat(objecttile): L3-5242 - make title truncate on 1 line

- src/components/Carousel/CarouselDots.tsx
- src/components/Carousel/_carousel.scss
[L3-5318](https://phillipsauctions.atlassian.net/browse/L3-5318)
https://github.com/user-attachments/assets/14e56a3e-3f6e-4bb6-b399-d4842497e518
**Figma link**
[Figma Link](https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium%3A-Tokens%2C-Components-%26-Patterns?node-id=5792-407&p=f&focus-id=4612-77094&m=dev)
**Summary** …
> fix(Pagination): L3-5318 Pagination Dot update to match iOS

- src/components/Button/_button.scss
- src/scss/_vars.scss
[L3-5301](https://phillipsauctions.atlassian.net/browse/L3-5301)
**Figma link**
[Figma Link](https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium%3A-Tokens%2C-Components-%26-Patterns?node-id=11989-21370&m=dev)
**Summary**
DO NOT MERGE. This PR adds a fix height to the button. I think putting explicit fixed height on button would be bad practice and lead to possible layout issues with icons. Height should be determined by font-size, line-height, padding, etc. If our heights are incorrect we should do an audit of what property is off. I have looked at the font-size and line-height for all breakpoints and our button follows figma spec. Need to check padding. 
This pull request includes a small change to …
> feat(button): L3-5301 - add button explicit height

- src/site-furniture/Header/_header.scss
[L3-5503](https://phillipsauctions.atlassian.net/browse/L3-5503)
| n/a | n/a |
**Figma link**
[n/a](https://www.figma.com/file/FIGMA-LINK)
**Summary**
Header is fixed instead of sticky
- src/site-furniture/Header/_header.scss: updated position to sticky
- you can't test from Seldon unless you can check dev tools
New Components
[L3-5503]: https://phillipsauctions.atlassian.net/browse/L3-5503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
> feat(_header.scss): L3-5503 fixed header

- src/patterns/SaleHeaderBanner/_saleHeaderBanner.scss
[L3-5344](https://phillipsauctions.atlassian.net/browse/L3-5344)
**Figma link**
**Summary**
In the Figma the location text has a spacing of 8px top and bottom.
Updated margin to match, remove ::before height from text below to match Figma
- Add step by step instructions on how …
> fix(SaleHeaderBanner): L3-5344 Padding inconsistent for the label section on the sale page banner

- src/components/SeldonImage/_seldonImage.scss
- src/patterns/SaleHeaderBanner/_saleHeaderBanner.scss
[L3-5191](https://phillipsauctions.atlassian.net/browse/L3-5191)
| ![image](https://github.com/user-attachments/assets/5b0bc940-a87a-449b-b75e-1d74014b7d61) | ![image](https://github.com/user-attachments/assets/224e5486-20d3-4b07-b78a-e3dee68f8f5d) |
**Figma link**
[Figma Link](https://www.figma.com/design/OvBXAq48blO1r4qYbeBPjW/RW---Sale-Page-(PLP)?node-id=3934-46010&m=dev)
**Summary**
Sale header banner was not respecting the 16/9 aspect ratio and needed a bottom border. This PR fixes the aspect ratio and adds a border
This pull request includes updates to the SCSS styling for the `SeldonImage` and `SaleHeaderBanner` components. The changes improve the handling …
> fix(imgsaleheaderbanner): L3-5191 - add bottom border and fix aspect ratio

- .storybook/main.ts
- package-lock.json
- package.json
- src/components/Input/Input.stories.tsx
- src/components/Input/Input.test.tsx
- src/components/Input/Input.tsx
- src/components/Select/Select.stories.tsx
- src/components/Select/Select.test.tsx
- src/components/Select/Select.tsx
- vite.config.ts
[L3-5461](https://phillipsauctions.atlassian.net/browse/L3-5461)
**Summary**
Allow the input to accept a react node as a label (for adding variable styles)
also, adding in storybook a11y add on https://storybook.js.org/docs/writing-tests/accessibility-testing#set-up-the-a11y-addon
which give you an overview of accessibility violations / passes …
> feat(input): L3-5461 react node as input label

- src/patterns/BidSnapshot/_bidSnapshot.scss
[L3-5596](https://phillipsauctions.atlassian.net/browse/L3-5596)
| ![image](https://github.com/user-attachments/assets/632e2600-fbc7-4e3a-b2aa-f097c5572d1e) | ![image](https://github.com/user-attachments/assets/fcd363b6-cd94-4b2e-9164-c1ad5211c135) |
**Figma link**
[n/a](https://www.figma.com/file/FIGMA-LINK)
**Summary**
fixed BidShapshot current bid spacing
- src/patterns/BidSnapshot/_bidSnapshot.scss: removed extra spacing
- verify that we don't have double spacing in BidShapshot
- Post …
> feat(_bidSnapshot): L3-5596 spacing fix

- src/components/Carousel/Carousel.stories.tsx
- src/components/Carousel/CarouselDots.tsx
- src/components/Carousel/_carousel.scss
[L3-5318](https://phillipsauctions.atlassian.net/browse/L3-5318)
https://github.com/user-attachments/assets/10f1fa33-b112-444c-9dce-4b3176b6fd21
**Figma link**
[Figma Link](https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium%3A-Tokens%2C-Components-%26-Patterns?node-id=5792-407&p=f&focus-id=4612-77094&m=dev)
**Summary**
Fixing a small regression in the carousel dot behavior
- Make sure values used to calculate scroll and max width of carousel dot containers are correct, lose the margin around the dots
- (Optional) Add verification steps to make sure this PR …
> fix(carousel): L3-5318 carousel dots

- src/components/Countdown/_countdown.scss
- src/patterns/SaleHeaderBanner/_saleHeaderBanner.scss
[L3-5595](https://phillipsauctions.atlassian.net/browse/L3-5595)
| ![image](https://github.com/user-attachments/assets/79c5a92c-136d-464a-b664-b32c867ca050) | ![image](https://github.com/user-attachments/assets/d2a58b2a-9c03-4a83-a9b7-c418d1bd7d37) |
**Figma link**
[Figma Link](https://www.figma.com/design/OvBXAq48blO1r4qYbeBPjW/RW---Sale-Page-(PLP)?node-id=255-40675&m=dev)
**Summary**
This PR corrects a few misalignments with the Figma design and the SaleHeaderBanner
This pull request includes changes to the SCSS files for the `Countdown` and `SaleHeaderBanner` components to improve their styling and layout.
Styling improvements:
* …
> fix(saleheaderbanner): L3-5595 - countdown fixes

- src/patterns/ObjectTile/_objectTile.scss
[L3-5604](https://phillipsauctions.atlassian.net/browse/L3-5604)
**Figma link**
**Summary**
Currently tag position is position absolute which will be wrong if the tile number is large such as in 3 digits.
Update position to relative so position can be correct with any tile number.
- Add step by step instructions on how to verify the …
> fix(ObjectTile): L3-5604 Update Seldon ObjectTile position fix

- src/patterns/BidSnapshot/BidSnapshot.test.tsx
- src/patterns/BidSnapshot/BidSnapshot.tsx
- src/patterns/ObjectTile/_objectTile.scss
[L3-5730](https://phillipsauctions.atlassian.net/browse/L3-5730)
| n/a | n/a |
**Figma link**
[n/a](https://www.figma.com/file/FIGMA-LINK)
**Summary**
minor logic change of displaying sold price
- src/patterns/BidSnapshot/BidSnapshot.tsx: removed `hasBids` from displaying sold price logic
- go to /?path=/docs/patterns-bidsnapshot--overview
- put lot status as past
- put numberOfBids as `0`
- verify that sold price is visible …
> feat(BidSnapshot): L3-5730 removed numberOfBids condition

- src/patterns/SaleHeaderBanner/SaleHeaderBanner.stories.tsx
- src/patterns/SaleHeaderBanner/_saleHeaderBanner.scss
[L3-5794](https://phillipsauctions.atlassian.net/browse/L3-5794)
| ![image](https://github.com/user-attachments/assets/75e710c8-bcbd-4212-8c66-f4dc2c73ad6a) | ![image](https://github.com/user-attachments/assets/1f44cd4e-48e2-49c8-a84f-d95e1d67dda7) |
**Figma link**
[Figma Link](https://www.figma.com/design/OvBXAq48blO1r4qYbeBPjW/RW---Sale-Page-(PLP)?node-id=1-8&p=f&m=dev)
**Summary**
Spacing fix
- Additions, Changes, and Removals. (You can use [GitHub Copilot PR Summary](https://docs.github.com/en/enterprise-cloud@latest/copilot/using-github-copilot/using-github-copilot-for-pull-requests/creating-a-pull-request-summary-with-github-copilot) to populate this …
> feat(_saleHeaderBanner): L3-5794 small spacing fix

- src/components/Drawer/_drawer.scss
[L3-5822](https://phillipsauctions.atlassian.net/browse/L3-5822)
| <img width="430" alt="Screenshot 2025-03-06 at 12 25 29 PM" src="https://github.com/user-attachments/assets/0ea05f70-217f-4d4c-a89a-6abea640c170" /> | <img width="425" alt="Screenshot 2025-03-06 at 12 22 52 PM" src="https://github.com/user-attachments/assets/80ebf7f1-6207-43b3-a308-145215bba4e5" /> |
**Summary**
Configure drawer to respect the height of dynamic mobile viewports
- Additions, Changes, and Removals. (You can use [GitHub Copilot PR Summary](https://docs.github.com/en/enterprise-cloud@latest/copilot/using-github-copilot/using-github-copilot-for-pull-requests/creating-a-pull-request-summa …
> fix(drawer): L3-5822 fix drawer on ios safari

- src/components/SeldonImage/_seldonImage.scss
- src/patterns/SaleHeaderBanner/SaleHeaderBanner.stories.tsx
[L3-5542](https://phillipsauctions.atlassian.net/browse/L3-5542)
| <img width="1697" alt="Screenshot 2025-03-03 at 12 34 25 PM" src="https://github.com/user-attachments/assets/fc6a402e-c5ef-41a0-b688-3457d7cd9f0a" /> | <img width="1652" alt="Screenshot 2025-03-03 at 12 36 09 PM" src="https://github.com/user-attachments/assets/8b5a8a6c-24d9-455f-aa67-7ec8d4bc33c8" /> |
**Summary**
Give max width to seldon image fallback for safari use cases
- Additions, Changes, and Removals. (You can use [GitHub Copilot PR Summary](https://docs.github.com/en/enterprise-cloud@latest/copilot/using-github-copilot/using-github-copilot-for-pull-requests/creating-a-pull-request-summary-w …
> fix(seldonimage): L3-5542 fallback image max width

- src/components/Button/Button.tsx
- src/components/IconButton/IconButton.tsx
- src/components/Pagination/Pagination.tsx
- src/components/Pagination/_pagination.scss
[L3-5701](https://phillipsauctions.atlassian.net/browse/L3-5701)
[L3-4468](https://phillipsauctions.atlassian.net/browse/L3-4468)
**Figma link**
**Summary**
Extend disabled states to the link pagination arrow components
- (Optional) Add verification steps to …
> feat(buttons): L3-5701 & L3-4468 lot pagination disabled state & padding updates

- src/components/Pagination/Pagination.stories.tsx
- src/components/Pagination/_pagination.scss
[L3-5701](https://phillipsauctions.atlassian.net/browse/L3-5701)
**Summary**
Pagination button disabled state was getting overridden in consumers …
> fix(pagination): L3-5701 fix disabled state on pagination

- src/components/Button/_button.scss
[L3-5317](https://phillipsauctions.atlassian.net/browse/L3-5317)
| ![image](https://github.com/user-attachments/assets/409ea81e-95d4-4699-aef2-63d460ebc124) | ![image](https://github.com/user-attachments/assets/11039db2-088e-40fd-a6d6-eacaa0027529) |
**Figma link**
[design Link](https://rive.app/s/wkN8U9Nxn0y3DXSC12hjkg/)
**Summary**
changed secondary button hover effect
- Additions, Changes, and Removals. (You can use [GitHub Copilot PR Summary](https://docs.github.com/en/enterprise-cloud@latest/copilot/using-gith
This pull request includes changes to the `src/components/Button/_button.scss` file to improve the styling and interaction of button components. The …
> feat(_button): L3-5317 fixed hover for secondary button

- src/components/Drawer/_drawer.scss
[L3-5957](https://phillipsauctions.atlassian.net/browse/L3-5957)
| 
| 
|
**Figma link**
[Figma Link](https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium%3A-Tokens%2C-Components-%26-Patterns?node-id=20973-67744&m=dev)
**Summary**
We're prepping to port over client portal components to seldon. Noticed some differences in drawer max width when confirming favorites drawer. Confirmed with design that the drawer should have a max-width of 480px 
This pull request includes a small change to the `src/components/Drawer/_drawer.scss` file. The change reduces the maximum width of the drawer component from 600px to 480px.
* …
> feat(drawer): L3-5957 Update drawer max width

- src/components/ContentPeek/ContentPeek.stories.tsx
- src/components/ContentPeek/ContentPeek.test.tsx
- src/components/ContentPeek/ContentPeek.tsx
- src/utils/constants.ts
[L3-5721](https://phillipsauctions.atlassian.net/browse/L3-5721)
| n/a | n/a |
**Summary**
fixed logic for rem units
- Additions, Changes, and Removal
This pull request includes changes to the `ContentPeek` component and its associated files to introduce support for height units and enhance functionality. The most important changes include adding the `HeightUnits` enum, updating the component's props and styles, and adding new tests.
Enhancements to `ContentPeek` component:
* [`src/components/ContentPeek/ContentPeek.tsx`](diffhunk://#diff-a1b5766242130234dd3ce61f2126dce07409153529063d7fd70a01260dfb69cfR10): Added support for height units by introducing the …
> feat(ContentPeek): L3-5721 fixed component's logic

- src/patterns/BidSnapshot/BidMessage.tsx
- src/patterns/BidSnapshot/_bidSnapshot.scss
[L3-6073](https://phillipsauctions.atlassian.net/browse/L3-6073)
| https://github.com/user-attachments/assets/ca76fca6-af3b-436a-aff7-e49c3e1fc989 | <img width="412" alt="Screenshot 2025-03-17 at 6 33 31 PM" src="https://github.com/user-attachments/assets/01a90743-e683-4477-a93a-9679f4d52b83" /> |
**Summary**
Take icon out of text in bid message so that it stacks correctly
- Take icon out of <Text> component in `BidMessage.tsx`
- Object tile looks ok
**Things to …
> fix(bidsnapshot): L3-6073 bid snapshot style fix

- src/patterns/ObjectTile/ObjectTile.tsx
- src/patterns/ObjectTile/_objectTile.scss
[L3-5542](https://phillipsauctions.atlassian.net/browse/L3-5542)
| <img width="411" alt="Screenshot 2025-03-17 at 3 31 30 PM" src="https://github.com/user-attachments/assets/0d890985-ebbc-4b43-8916-2f60262a3c99" /> | <img width="419" alt="Screenshot 2025-03-17 at 3 32 11 PM" src="https://github.com/user-attachments/assets/deba04fd-9d54-4838-9e4d-90e12b6096b9" /> |
**Figma link**
[Figma Link](https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium%3A-Tokens%2C-Components-%26-Patterns?m=auto&node-id=10838-22188)
**Summary**
Updating tokens in Object Tile, remove wrapping span in Text component
- Update tokens for lot number & maker in object tile
- …
> fix(objecttile): L3-5542 object tile style fixes

- src/components/Button/_button.scss
- src/scss/_vars.scss
[L3-6070](https://phillipsauctions.atlassian.net/browse/L3-6070)
**Figma link**
[Figma Link](https://www.figma.com/design/dGJDhTBtxCrcPrdo6Dl9DN/RW---LIVE-Lot-Details-(PDP)?t=cAmDtSPqdcCuGTq6-0)
**Summary**
Added new tokens for vertical padding and fixed buttons height using padding
- src/scss/_vars.scss: added new token
- src/components/Button/_button.scss: fixed height
- go to button and verify that md height is 48px and xl is 52px
New Components
[L3-6070]: …
> feat(_button): L3-6070 fixed height of button

- src/components/Search/Search.test.tsx
- src/components/Search/Search.tsx
- src/scss/_vars.scss
[L3-5572](https://phillipsauctions.atlassian.net/browse/L3-5572)
https://github.com/user-attachments/assets/de3c9057-4a28-4e63-8b86-2190618e8c60
**Figma link**
**Summary**
Updated Search Bar to remain open with typed in search until the new page loads
- …
> fix(Search): L3-5572 Search Bar Removing Typed Search

- src/components/Accordion/Accordion.test.tsx
- src/components/Accordion/AccordionItem.test.tsx
- src/components/Button/Button.stories.tsx
- src/components/IconButton/IconButton.stories.tsx
- src/components/SeldonImage/SeldonImage.test.tsx
- src/patterns/ObjectTile/ObjectTile.stories.tsx
- src/patterns/Social/Social.stories.tsx
- src/site-furniture/Footer/Footer.stories.tsx
- src/site-furniture/Header/Header.stories.tsx
- src/site-furniture/Header/Header.test.tsx
- src/story-styles.scss
[L3-3417](https://phillipsauctions.atlassian.net/browse/L3-3417)
**Summary**
Part 4/4 of the changes for the Sale and Lot icon changes. This PR contains all of the story and test updates to support the `Icon` changes
This pull request includes several changes to the codebase, primarily focusing on updating the usage of icons across various components and tests. The main changes involve replacing direct SVG imports with the `Icon` component and updating corresponding test cases.
* [`src/components/Button/Button.stories.tsx`](diffhunk://#diff-041d3d3c1a5b937a23eb07a03262a56b25f82b9cffccdbd7bea8ace94eddd35cL4-R5): Replaced direct import of `Plus` SVG with `Icon` component in `ButtonWithIcon` story. …
> feat(Icon): L3-3417 Part 4 - test and story updates

- src/assets/icons.ts
- src/assets/menu.svg
- src/componentStyles.scss
- src/components/TextArea/TextArea.stories.tsx
- src/components/TextArea/TextArea.test.tsx
- src/components/TextArea/TextArea.tsx
- src/components/TextArea/_textArea.scss
- src/components/TextArea/index.ts
- src/index.ts
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/TICKET-ID)
**Figma link**
[Figma Link](https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium%3A-Tokens%2C-Components-%26-Patterns?node-id=12131-1636&m=dev)
**Summary**
Add textarea component, used in create/edit lists drawer 
This pull request introduces the new `TextArea` component along with its associated styles, stories, tests, and exports. The most important changes include adding the `TextArea` component, updating the styles, and integrating the component into the existing project structure.
New `TextArea` component:
* [`src/components/TextArea/TextArea.tsx`](diffhunk://#diff-97f6d5d559cc8e90507a1d113df11172dadfb0d81403 …
> feat(textarea): L3-5975 Add textarea component

- src/design/icons/IconGrid.tsx
[L3-3417](https://phillipsauctions.atlassian.net/browse/L3-3417)
**Summary**
I think my Icons pr got merged around the same time as another change that added `id` as a required prop to `Input` and `Select`, so my original L3-3417 PR got merged, but the publish job failed. This should hopefully fix it so my changes can get published
This pull request includes changes to the `IconGrid` component in the `src/design/icons/IconGrid.tsx` file to improve accessibility by adding `id` attributes to form elements.
Accessibility improvements:
* Added `id` attributes to the `Input` elements for height and width, and to the `Select` element for color in the `IconGrid` component.
- Add …
> fix(IconGrid): L3-3417 fix build issue

- src/patterns/ObjectTile/ObjectTile.tsx
[L3-6287 ](https://phillipsauctions.atlassian.net/browse/L3-6287 )
**Summary**
This pull request includes a small change to the `ObjectTile` component in the `src/patterns/ObjectTile/ObjectTile.tsx` file. The change allows the `titleText` property to accept either a string or a `React.ReactNode`.
* [`src/patterns/ObjectTile/ObjectTile.tsx`](diffhunk://#diff-8ed75c9c4bf0426a7e652657576880a82efc966be04761f900f967a445a6ee5bL82-R82): Modified the `titleText` property in the `ObjectTileProps` interface to accept a `string` or a `React.ReactNode`.
- Additions, Changes, and Removals. (You can use [GitHub Copilot PR Summary](https://docs.github.com/en/enterprise-cloud@latest/copilot/using-github-copilot/using-github-copilot-f …
> fix(lot-description): L3-6287 Fix for Object Tile Title Text

- src/componentStyles.scss
- src/components/Icon/_icon.scss
- src/design/icons/icons.mdx
[L3-6336](https://phillipsauctions.atlassian.net/browse/L3-6336)
| ![image](https://github.com/user-attachments/assets/1aa12ee5-b704-4928-82c1-a61ac6abebb9) | ![image](https://github.com/user-attachments/assets/1f2de6eb-4838-4f72-9986-633acccdee17) |
**Figma link**
[Figma Link](https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium%3A-Tokens%2C-Components-%26-Patterns?node-id=4530-104045&p=f&m=dev)
**Summary**
The chevron icon is not of a 1x1 ratio so was getting really tall because only `max-width` was set.  It was also not centered
This pull request includes changes to the styling and usage of the `Icon` component. The most important changes …
> fix(icon): L3-6336 handle icons that are not of 1x1 aspect ratio

- src/components/Tabs/_tabs.scss
[L3-5252](https://phillipsauctions.atlassian.net/browse/L3-5252)
| ![Screenshot 2025-04-02 145849](https://github.com/user-attachments/assets/c7dd3e07-2d19-4a88-8864-2ba94d90883b) | ![Screenshot 2025-04-02 145930](https://github.com/user-attachments/assets/1a229b2b-f878-4c03-be5e-dc0b722d0374) |
**Figma link**
**Summary**
Tab trigger label weight now applied even when tab is not the active tab
This pull request includes changes to the `src/components/Tabs/_tabs.scss` file to improve the styling of tabs. The most important changes involve adjustments to the font weight settings.
Styling improvements:
* Added …
> fix(tab-triggers): L3-5252 Tab Inactive Label Weight Fix

- src/components/Tabs/_tabs.scss
[L3-5827](https://phillipsauctions.atlassian.net/browse/L3-5827)
| ![Tabs button hover before](https://github.com/user-attachments/assets/b539f26f-c24d-468b-9a39-bb36f373b2a6) | ![Tabs button hover after](https://github.com/user-attachments/assets/b9d79be0-05ce-47fa-a1d7-83b50b417a36) |
**Figma link**
[Figma Link](https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium--Tokens--Components---Patterns?node-id=11411-13647&m=dev)
**Summary**
sale page hovering over selected tab should not change UX
Updated css to not add hover state on active tab. …
> fix(Tabs): L3-5827 Update active state of Tabs hover state

- src/components/PinchZoom/PinchZoom.stories.tsx
- src/components/PinchZoom/_pinchZoom.scss
[L3-4672](https://phillipsauctions.atlassian.net/browse/L3-4672)
https://github.com/user-attachments/assets/81df7d34-d1e1-4a80-80d9-e4b336f9fb4b
**Figma link**
**Summary**
Removed unnecessary white space in the Pinch Zoom
This pull request includes several changes to improve the styling and image handling in the `PinchZoom` and `SeldonImage` components, as well as a minor update …
> feat(PinchZoom): L3-4672 fixed unnecessary white space

- src/componentStyles.scss
- src/components/Loader/Loader.stories.tsx
- src/components/Loader/Loader.tsx
- src/components/Loader/loader.scss
[L3-5951](https://phillipsauctions.atlassian.net/browse/L3-5951)
https://github.com/user-attachments/assets/f874a67b-aa20-4ef0-8fdc-c630ee8c447d
This pull request introduces a new `Loader` component to the project, including its styles, implementation, and Storybook configuration. The most important changes are summarized below:
* [`src/components/Loader/Loader.tsx`](diffhunk://#diff-6b7479193567a5909c1dd1be0d0e89f916fb640b1d2afff2d7de9c84c3214b72R1-R10): Added the `Loader` component implementation using `forwardRef` and `HTMLProps` from React, along with a class name and test ID.
* [`src/components/Loader/loader.scss`](diffhunk://#diff-876df5656c54318592244ec38d3f9b37c1a9d73954838e9300d6f20d559920b1R1-R25): Created a new SCSS file for the `Loader` …
> feat(Loader): L3-5951 Loading Spinner Component

- src/patterns/ObjectTile/_objectTile.scss
[L3-5631](https://phillipsauctions.atlassian.net/browse/L3-5631)
| ![image](https://github.com/user-attachments/assets/60f59f71-e4fe-4f04-b152-84d35f959c1a) | ![image](https://github.com/user-attachments/assets/12467a50-2182-45c6-a3fa-24b23484f3d7) |
**Figma link**
**Summary**
Adds a min-height to the container that holds the "No Reserve" text on the Object Tile to ensure that space is always preserved.
This pull request includes a small change to the `src/patterns/ObjectTile/_objectTile.scss` file. The change removes the `&__badge:empty` style rule, which previously set a `min-height` for empty badge elements, …
> fix(ObjectTile): L3-5631 reserve space for 'No Reserve' on ObjectTile

- src/components/Countdown/Countdown.stories.tsx
- src/components/Countdown/Countdown.test.tsx
- src/components/Countdown/Countdown.tsx
- src/components/Countdown/_countdown.scss
- src/components/Countdown/_duration.scss
- src/patterns/BidSnapshot/BidSnapshot.tsx
- src/site-furniture/Footer/Footer.tsx
[L3-6269](https://phillipsauctions.atlassian.net/browse/L3-6269)
https://github.com/user-attachments/assets/1b46745d-e079-40c5-8b09-d5744af2ef43
**Figma link**
[Figma Link](https://www.figma.com/design/hxqgsE26wM7hII0WaUaDfF/RW---TIMED-Lot-Details--PDP-?t=fbOiFWsATS4NL8uF-0)
**Summary**
Added closing state to the timer
variant={CountdownVariants.compact} was removed because on SalePage in remix it was showing text in black font color and countdown in red which verified by EVB wasn't correct way to display it
the correct way to display everything in red font color
- Additions, Changes, and Removals. (You can use [GitHub Copilot PR Summary](https://docs.github.com/en/enterprise-cloud@latest/copilot/using-github-copilot/ …
> feat(countdown): L3-6269 added closing state

- src/components/Navigation/NavigationItemTrigger/NavigationItemTrigger.tsx
- src/components/Navigation/NavigationList/_navigationList.scss
- src/site-furniture/Header/Header.stories.tsx
- src/utils/index.tsx
- src/utils/utils.test.tsx
[L3-4155](https://phillipsauctions.atlassian.net/browse/L3-4155)
https://github.com/user-attachments/assets/0388c8aa-ba9c-4dec-8c20-7c506aafc9b8
**Figma link**
**Summary**
Created a function to focus and de-focus on element by Id
This pull request introduces a new utility function, `focusElementById`, to manage focus and blur states for DOM elements by their IDs. It also integrates this function into the `NavigationItemTrigger` component to improve accessibility by automatically focusing or blurring submenu elements based on their open state. Additionally, unit tests have been added to ensure the correctness of the new utility function.
* **Focus Management in …
> feat(utils): L3-4155 Header z index issues on sale and lot pages and references to an old class

- .github/CODEOWNERS
- src/patterns/UserManagement/UserManagement.tsx
- src/patterns/UserManagement/_userManagement.scss
[L3-4229](https://phillipsauctions.atlassian.net/browse/L3-4229)
| ![image](https://github.com/user-attachments/assets/3b7ffe3a-0cd4-4da4-baa7-d51ef0c11052) | ![Screenshot 2025-05-01 170237](https://github.com/user-attachments/assets/8a3576b3-f3e0-4d8f-a5bb-819f2bf1ae9c) | 
**Figma link**
**Summary**
The Account icon was being rendered at 16x16 for all layouts, but it should be 16x16 on desktop and 24x24 for mobile. This fixes the issue by using `SSRMediaQuery.Media` to render the icon at the appropriate size for each layout
This pull request introduces a responsive enhancement to the `UserManagement` component …
> fix(UserManagement): L3-4229 make account icon responsive

- src/components/Navigation/NavigationItemTrigger/_navigationItemTrigger.scss
[L3-6500](https://phillipsauctions.atlassian.net/browse/L3-6500)
https://github.com/user-attachments/assets/0bd446c1-84e5-4c8b-ad5f-fcd795a2fc39
**Figma link**
**Summary**
The cursor now only change when hovering on a navigation link in the header.
This pull request introduces a minor update to the `_navigationItemTrigger.scss` file. The change ensures that the cursor is set to `default` when hovering over the `&__submenu` element within the `&--hovered` state.
- (Optional) Add verification steps to make sure this PR doesn't break old …
> fix(Header): L3-6500 Fix hover state

- src/patterns/AccountPageHeader/AccountPageHeader.stories.tsx
- src/patterns/AccountPageHeader/AccountPageHeader.test.tsx
- src/patterns/AccountPageHeader/AccountPageHeader.tsx
- src/patterns/AccountPageHeader/_accountPageHeader.scss
[L3-6694](https://phillipsauctions.atlassian.net/browse/L3-6694)
| ![image](https://github.com/user-attachments/assets/5f3001dd-18aa-411a-abc2-c3eea23fc2c4) ![image](https://github.com/user-attachments/assets/fbbf326e-3548-4462-91d9-f72671e66ab9)| 
**Figma link**
**Summary**
- Small tweaks to the component: fix typing, make prop names more clear, small css alignment update
This pull request refactors the `AccountPageHeader` component by replacing the `subheader` prop with a new `subtitle` prop, updating related files, and making minor adjustments to the component's structure and styles. It also enhances the …
> fix(pageHeaderComponent): L3-6694 small misalignment in account page header component

- src/components/ComboBox/ComboBox.stories.tsx
- src/components/ComboBox/ComboBox.tsx
[L3-6753](https://phillipsauctions.atlassian.net/browse/L3-6753)
Updates:
Made ( No Option ) message translate-able
Add a container prop to ComboBox to work with popover ref, to prevent portal conflicts. 
https://github.com/user-attachments/assets/c197ce53-e6f2-49ef-881b-a058b4baa687
**Figma link**
**Summary**
This pull request introduces a new feature that allows the `ComboBox` component to be embedded within a `Drawer` and enhances its configurability. Key changes include the addition of a `popoverContainerRef` prop for better control over the ComboBox's popover container, a customizable "no options" message, and a new story in Storybook to demonstrate the ComboBox inside a Drawer.
* Added a new `popoverContainerRef` …
> fix(ComboBox): L3-6753 add new props

- src/components/Navigation/NavigationItem/_navigationItem.scss
[L3-6783](https://phillipsauctions.atlassian.net/browse/L3-6783)
https://github.com/user-attachments/assets/ded9feb3-d717-4e10-8aef-ed170ebca53a
**Figma link**
**Summary**
This pull request includes a minor update to the styling of navigation items in the `_navigationItem.scss` file. The change moves the `cursor: pointer` property from the `.nav__item` class to the `button` element inside it.
Styling adjustments:
* [`src/components/Navigation/NavigationItem/_navigationItem.scss`](diffhunk://#diff-aa671559b9ae7e8c0a3066fde9d3b009f41933669abc21e9e62763bf6cbd2edbL4-L5): Removed `cursor: pointer` from the `.nav__item` class and added it to the `button` element for better specificity and alignment with the …
> fix(Header): L3-6783 Hover state on header link cursor pointer 

- src/patterns/BidSnapshot/BidSnapshot.tsx
[L3-6782](https://phillipsauctions.atlassian.net/browse/L3-6782)
https://github.com/user-attachments/assets/0c886e19-6d42-419d-92b0-a3c491659eb4
**Summary**
This pull request includes a small but important change to the `BidSnapshot` component. The change ensures that the starting bid is only displayed when it has a valid value, improving the component's conditional rendering logic.
* [`src/patterns/BidSnapshot/BidSnapshot.tsx`](diffhunk://#diff-023608454dd8a373f83e678913fe1db898600977d93505f7afa1ff759b3c3e59L166-R166): Updated the conditional rendering logic to check for a valid `startingBid` value before displaying it, ensuring accurate and meaningful UI behavior.hanges that were made and explanation of WHY they were made
**Change List (describe the changes made to the …
> feat(BidSnapshot): L3-6782 added condition

- src/components/Countdown/Countdown.stories.tsx
- src/components/Countdown/Countdown.tsx
- src/patterns/BidSnapshot/BidSnapshot.tsx
- src/patterns/SaleHeaderBanner/SaleHeaderBanner.stories.tsx
- src/patterns/SaleHeaderBanner/SaleHeaderBanner.tsx
[L3-6795](https://phillipsauctions.atlassian.net/browse/L3-6795)
**Summary**
The countdown incremenation logic changed [here](https://github.com/PhillipsAuctionHouse/seldon/pull/613), but it seems to be causing this weird behavior whenever the end time received updated (as in popcorn bidding)
To simplify, I reverted back to the previous incrementation logic, but this time using a custom date getter as a prop, so that it's more 1:1 with the previous logic but using the date getter (which consumers will use to pass the correct time with respect to an offset, for example)
-This pull request introduces several updates to the `Countdown`, `BidSnapshot`, and `SaleHeaderBanner` components, focusing on improving flexibility …
> fix(countdown): L3-6795 fix glitchy countdown logic

- src/components/Loader/Loader.tsx
- src/components/Loader/_loader.scss
- src/components/Loader/index.ts
- src/components/Loader/loader.scss
- src/index.ts
[L3-6809](https://phillipsauctions.atlassian.net/browse/L3-6809)
Added missing export
Fixed import scss file names
Linter changed some of the import order by ordering alphabetically. 
**Summary**
This pull request updates the `src/index.ts` file to reorganize and add exports for several components. The changes primarily focus on ensuring consistency in the exported components and improving the structure of the file.
* Added export for `Loader` component from `./components/Loader/Loader`.
* Re-added exports for `AddToCalendar`, `AuctionTile`, and `Pictogram` components, which were previously removed, ensuring they are now consistently available.
- Additions, Changes, and Removals. (You can use [GitHub Copilot PR …
> fix(Loader): L3-6809 missing component export

- src/components/AddToCalendar/AddToCalendar.stories.tsx
- src/components/AddToCalendar/AddToCalendar.tsx
- src/components/AddToCalendar/_addToCalendar.scss
- src/components/AddToCalendar/calendarLinks.test.ts
- src/components/AddToCalendar/calendarLinks.ts
- src/components/AddToCalendar/types.ts
- src/components/IconButton/IconButton.tsx
…es with dropdown
[L3-5753](https://phillipsauctions.atlassian.net/browse/L3-5753)
| ![image](https://github.com/user-attachments/assets/309fc4a7-d41d-4251-9df9-1ed1d37c3834) | ![image](https://github.com/user-attachments/assets/56bf3f3f-993f-4e66-bd8b-c57b8e533e2f) |
**Figma link**
[Figma Link](https://www.figma.com/design/OvBXAq48blO1r4qYbeBPjW/RW---Sale-Page--PLP-?node-id=4791-30655&p=f&m=dev)
**Summary**
Update dropdown hover and focus styles to match with Seldon dropdown component.
Update end date type to accept null value.
- Additions, Changes, and Removals. (You can use [GitHub Copilot PR Summary](https://docs.github.com/en/enterprise-cloud@latest/copilot/us …
> feat(AddToCalendar): L3-5753 Update code to accept end date as null value and match styles with dropdown

- src/patterns/FavoritesCollectionTile/FavoritesCollectionTile.stories.tsx
- src/patterns/FavoritesCollectionTile/FavoritesCollectionTile.test.tsx
- src/patterns/FavoritesCollectionTile/FavoritesCollectionTile.tsx
- src/patterns/FavoritesCollectionTile/_favoritesCollectionTile.scss
[L3-6739](https://phillipsauctions.atlassian.net/browse/L3-6739)
Changes:
1. Popover menu no longer cut off by the viewport
2. Link element text no longer has `text-transform: capitalize`
3. Text within tile now has padding space from the border
4. Empty list tile now have background color
5. The count text for an empty list read “0 LOTS” instead of “0 LOT
6. The kebab button for the context menu now aligned with the list title
7. “Favorites” variant now does not have kebab menu
8. If `name` is empty string and count is 0 tile displays the "Create your first list" state for list variant
9. Remove Icon hover text
10. Added custom class for Link component
**Figma link**
**Summary**
This pull request …
> fix(FavoritesCollectionTile): L3-6739 Small issues

- src/components/ComboBox/ComboBox.test.tsx
- src/components/ComboBox/ComboBox.tsx
- src/components/PhoneNumberPicker/PhoneNumberPicker.stories.tsx
- src/components/PhoneNumberPicker/PhoneNumberPicker.test.tsx
- src/components/PhoneNumberPicker/PhoneNumberPicker.tsx
- src/utils/usePrevious.ts
[L3-6763](https://phillipsauctions.atlassian.net/browse/L3-6763)
**Summary** …
> L3 6781 combobox reset on exit

- package-lock.json
- src/components/SaleCard/SaleCard.stories.tsx
- src/components/SaleCard/SaleCard.tsx
- src/components/SaleCard/_saleCard.scss
- src/components/SaleCard/index.ts
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/TICKET-ID)
| ![image](https://github.com/user-attachments/assets/ea2c17f7-3bcf-4016-b144-1ef7facd559f) | ![image](https://github.com/user-attachments/assets/7b7e0a6f-167a-4a77-b97a-46551da0e471) |
**Figma link**
[Figma Link](https://www.figma.com/design/H1kCh6MXU8jasYbQuCbyBt/Calendar?node-id=2141-265691&m=dev)
**Summary**
Update Sale card component based on review from designer.
- Updated format for variant names:
- SaleCard[With|No][Feature/Modifier]
- Updated Title font size to be Heading 4 (20px) across all card types.
- Link text updated to sentence case, following the designs.
- Updated Related …
> feat(Salecard): L3-6924 Salecard review updates

- src/components/SaleCard/SaleCard.tsx
- src/components/SaleCard/_saleCard.scss
[L3-7218](https://phillipsauctions.atlassian.net/browse/L3-7218)
| <img width="3000" height="800" alt="image" src="https://github.com/user-attachments/assets/494ae0e4-8a7b-40d6-9af5-0f95c7761f39" /> | <img width="2585" height="380" alt="image" src="https://github.com/user-attachments/assets/39737976-a26c-4eb3-ac5e-622f564ad9aa" /> |
**Figma link**
[Figma Link](https://www.figma.com/design/H1kCh6MXU8jasYbQuCbyBt/Calendar?node-id=4768-18758&m=dev)
**Summary**
Update badge label size for related sale variant
- Additions, Changes, and Removals. (You can use [GitHub Copilot PR Summary](https://docs.github.com/en/enterprise-cloud@latest/copilot/using-github-copilot/using …
> feat(RelatedSale): L3-7218 Update auctio type font size

- src/index.ts
[L3-6952](https://phillipsauctions.atlassian.net/browse/L3-6952)
**Figma link**
**Summary**
Added missing exitgatecard import to index file.
- (Optional) Add verification steps to …
> feat(ExitgateCard): L3-6952 Add missing import to index

- src/components/Icon/_icon.scss
[L3-7333](https://phillipsauctions.atlassian.net/browse/L3-7333)
| <img width="442" height="421" alt="image" src="https://github.com/user-attachments/assets/aa991318-34aa-4d75-801d-499c1a1ba0d2" /> | <img width="447" height="214" alt="image" src="https://github.com/user-attachments/assets/9ea0ecc3-fc68-4f58-af0d-508906e2a5b8" /> |
**Summary**
On Safari and iOS Chrome, icons need not just a `max-width` specified but a `width` specified to render.
This pull request includes a small update to the `_icon.scss` file to improve the responsiveness of SVG icons.
* [`src/components/Icon/_icon.scss`](diffhunk://#diff-bf9ec38858076ebb920d6bf08f4f0e49e7563af43c0de37ede8124dd22 …
> fix(icon): L3-7333 set width correctly for safari

- src/components/Icon/_icon.scss
This reverts commit 1f54c0ea8f139748f23ef8102ec0c3e326fdb15e.
[L3-7333](https://phillipsauctions.atlassian.net/browse/L3-7333)
**Summary**
The fix to make the footer social icons responsive broken many other places icons are being used without explicitly setting width from Seldon.  I'm going to back out the change for now to see if there's a better way to fix it.
- Add step by step …
> fix(icon): L3-7333 Revert set width correctly for safari (#661)

- src/patterns/SaleHeaderBanner/SaleHeaderBanner.stories.tsx
- src/patterns/SaleHeaderBanner/SaleHeaderBanner.tsx
- src/patterns/SaleHeaderBanner/_saleHeaderBanner.scss
[L3-7403](https://phillipsauctions.atlassian.net/browse/L3-7403)
**Figma link**
[Figma Link](https://www.figma.com/design/H1kCh6MXU8jasYbQuCbyBt/Calendar?node-id=3905-25596&m=dev)
**Summary**
Adding the ability to add a badge to the Sale Header Banner, which is needed for auctions that accept consignments (part of the Calendar Epic)
This pull request adds support for displaying a custom badge text in the `SaleHeaderBanner` component. It introduces a new optional `badgeText` prop, updates the component and its stories to utilize this prop, and adds corresponding styles for the badge display.
**Component enhancements:**
* Added an optional `badgeText` prop to the `SaleHeaderBannerProps` interface and …
> feat(SaleHeaderBanner): L3-7403 add badgeText prop to SaleHeaderBanner

- src/components/NotificationBanner/NotificationBanner.stories.tsx
- src/components/NotificationBanner/_notificationBanner.scss
- src/scss/_vars.scss
[L3-7547](https://phillipsauctions.atlassian.net/browse/L3-7547)
Added style to Notification Banner's children's style based on Figma.
**Figma link**
[Figma Link](https://www.figma.com/design/qEd5aXjQeiboeJ8GJMOJba/Global-Notification-Banner?node-id=1-1830&m=dev)
**Summary**
- Add step by step instructions on how …
> fix(NotificationBanner): L3-7547 Add Notification Banner child style

- src/assets/formatted/IconBlueCircle.tsx
- src/assets/formatted/index.ts
- src/assets/icon-blue-circle.svg
[PHOENIX-2071](https://phillipsauctions.atlassian.net/browse/PHOENIX-2071)
| <img width="371" height="189" alt="Screenshot 2025-08-21 at 6 55 52 PM" src="https://github.com/user-attachments/assets/1ad2a6c0-f7fa-4948-8df5-faed5afa5881" /> | P<img width="513" height="209" alt="Screenshot 2025-08-21 at 6 55 49 PM" src="https://github.com/user-attachments/assets/149c7c19-9667-4a72-a4d8-e5eba6445c61" /> |
**Figma link**
**Summary**
Added new icon
- Additions, Changes, and Removals. (You can use [GitHub Copilot PR Summary](https://docs.github.com/en/enterprise-cloud@latest/copilot/using-github-copilot/using-github-copil …
> feat(icons): PHOENIX-2071 adding icon

- src/components/NotificationBanner/_notificationBanner.scss
- src/scss/_vars.scss
[L3-7564](https://phillipsauctions.atlassian.net/browse/L3-7564)
**Summary**
Notification banner is covering the bidding modal adjusted the banner's z-index in this PR to update legacy/remix
- Post logs, …
> fix(NotificationBanner): L3-756 Notification banner is covering the bidding modal

- src/patterns/SaleCard/SaleCard.stories.tsx
- src/patterns/SaleCard/_saleCard.scss
[L3-7372](https://phillipsauctions.atlassian.net/browse/L3-7372)
| <img width="3775" height="1822" alt="Calendar before center pinning image" src="https://github.com/user-attachments/assets/2dc2cdb8-bcdc-4705-b350-1cd7b7bb363b" /> | <img width="3722" height="1797" alt="image" src="https://github.com/user-attachments/assets/f42ad6e6-0099-457b-8494-2b84c37f53c7" /> |
https://github.com/user-attachments/assets/e98bde26-b8b9-419d-8cb9-7896a50cf5f5
**Figma link**
[Figma Link](https://www.figma.com/design/H1kCh6MXU8jasYbQuCbyBt/Calendar?node-id=4768-18772&m=dev)
**Summary**
Center pin Sale card image and make image resizing responsive using flex
- Additions, Changes, …
> feat(Salecard): L3-7372 Center pin banner image

- src/patterns/UserManagement/_userManagement.scss
[L3-7579](https://phillipsauctions.atlassian.net/browse/L3-7579)
| <img width="594" height="560" alt="image" src="https://github.com/user-attachments/assets/85cb53de-bcc0-4994-a160-1b62e6f065cf" /> | <img width="597" height="459" alt="image" src="https://github.com/user-attachments/assets/dc9bd001-2dbc-4d96-b57c-511ea2d0b4a3" /> |
**Figma link**
n/a
**Summary**
- Remove “Account” copy is showing next to icon. Text is no longer a <p
This pull request makes a minor update to the `src/patterns/UserManagement/_userManagement.scss` stylesheet. The change improves CSS selector specificity by removing the unnecessary `p` element selector, ensuring that the styles apply …
> feat(header): L3-7579 Mobile Web | Account icon is not displaying correctly on Remix pages

- src/patterns/SaleCard/SaleCard.stories.tsx
- src/patterns/SaleCard/SaleCard.test.tsx
- src/patterns/SaleCard/SaleCard.tsx
[PHOENIX-2233](https://phillipsauctions.atlassian.net/browse/PHOENIX-2233)
**Figma link**
[Figma Link](https://www.figma.com/design/5tWA2WhbnE2xoka58zArld/A---T-C-at-the-Beginning?node-id=3090-16197&m=dev)
**Summary**
We need a simpler version of the SaleCard without image for the Live Saleroom Sale Card
This pull request enhances the `SaleCard` component by making the `imageSrc` prop optional, allowing the card to be rendered without an image. It also adds a new Storybook story and a test case to verify this behavior.
**SaleCard image handling improvements:**
* Made the `imageSrc` prop in `SaleCardProps` optional, enabling the component to be used without an image.
* Added a new Storybook story, …
> feat(salecard): PHOENIX-2233 allow imageSrc to be optional property

- src/components/Carousel/Carousel.stories.tsx
- src/components/Carousel/Carousel.tsx
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/PHOENIX-2082)
**Figma link**
**Summary**
Added multiple carousel example
This pull request adds support for scrolling multiple items at once in the `Carousel` component and introduces a new story to demonstrate this functionality. The main changes include updating the component props, passing the new prop through context, and providing an example usage.
**Feature: Multiple items scroll support**
* Added a new `slidesToScroll` prop to the `CarouselProps` interface in `Carousel.tsx`, allowing consumers to specify how many items to scroll at once.
* Set a default value for `slidesToScroll` …
> feat(Carousel): PHOENIX-2082 added scroll multiple slides capability

- src/design/colors-tokens/ColorTokensPage.tsx
- src/scss/_sharedClasses.scss
- src/scss/_vars.scss
[L3-7141](https://phillipsauctions.atlassian.net/browse/L3-7141)
| <img width="311" height="81" alt="image" src="https://github.com/user-attachments/assets/27b0dcf4-a836-4ec0-a7fd-362a26f20de3" /><img width="206" height="80" alt="image" src="https://github.com/user-attachments/assets/c963005e-0f2f-4fc1-97c9-40acd1d93840" /> | <img width="257" height="105" alt="image" src="https://github.com/user-attachments/assets/e41fd6ec-c6ea-4883-b026-fc801c8cac3a" /><img width="172" height="84" alt="image" src="https://github.com/user-attachments/assets/0ce63d35-50fc-4c03-867b-9efaa70ef773" />|
**Figma link**
n/a
**Summary**
- Fix skeleton loader colors for button 
- Update $highlight-purple per design request
**Change List …
> feat(colorTokens): L3-7141 Token mapping fixes
