PhillipsAuctionHouse/seldon

.github/workflows/publish.yml
**Summary**
-  Add PAT to publish script in order to bypass the "require pull request" branch protection in our CI environment
=> chore: use PAT to bypass the protected branch rule for deploy

.husky/commit-msg, package-lock.json, package.json
**Summary**
In order to enforce the commit messages necessary for our semantic versioning tooling I am adding Commitlint to the repo. 
**Changes**
- add [commitlint](https://github.com/conventional-changelog/commitlint) package to repo
- added [husky](https://github.com/typicode/husky) to run on commit git hook
- added configuration files of both
=> Add `commitlint` to the repo

.github/workflows/publish.yml
**Summary**
- Husky is causing the publish build step to exit with non zero. Turning husky off in ci
=> Turn off husky in ci and trigger release

src/components/HeroBanner/_heroBanner.scss
Closes [WEB-8741](https://phillipsauctions.atlassian.net/browse/WEB-8741)
**Summary**
- Fix for margin issue on mobile. Removed unnecessary media query affecting pre head and post head margins
- Removed media query (_heroBanner.scss)
- Check margin spacing for pre head and post head on mobile screen size
- N/A
=> Web 8741 Ensure padding between prehead and title in banners

package.json, vite.config.ts
**Summary**
Added a common js build option to our config for issues I was having in the Remix project. 
- Added a section to vite.config.js to build a cjs version
- updated Packages.json `main` field to point to the cjs version.
- tests here
- We need to test this on Phillips Web just to be sure we are not breaking the import in that project. 
=> Add commonjs build to our package

package-lock.json, package.json, vite.config.ts
Closes #
**Summary**
-  tweak build settings to stop bundling classnames
- swapped classnames from a devDep to a depenedency in package.json
- listed deps as external in our build config in vite.config.ts
We will need to test this release for regressions in phillips-public
=> fix: tweak build settings to stop bundling classnames

CHANGELOG.md, package.json, vite.config.ts
Closes #
**Summary**
- Troubleshooting issues stemming from classnames being a commonjs modulle.
- change build output to mjs. Make changes to references in package.json
- update vite.config.ts to outpput mjs files
- tests here
- tests here
=> fix: still troublshooting build

CHANGELOG.md, package.json, src/styles.scss, vite.config.ts
Closes #
**Summary**
- Previous PRs added changes to our config to deal with SSR in our remix application and the commonjs deps we ship along with this library. I was able to alter config in the remix project that should negate the need for these changes. Undoing here to ensure compatibility with the Phillips-web project. 
- Changed `vite.config.ts` to no longer output `mjs` file
- removed the import of our datepicker sass partial as the component is not exported from this library yet.
- Changed the `package.json` to no longer reference the `.mjs` entry 
As long as our checks all pass here this should be good. We need to pull in latest in Phillips-web to be sure that build still works with …
=> Undo build config changes that were unnecessary 

src/components/Input/_input.scss, src/scss/_vars.scss
**Summary**
Simple update to error styling for inputs
- Colored border and inset box-shadow applied to input field
- Removal of color applied to input label when in error state
- Addition of error-pink color variable
View input component with invalid property set to true
Only styling is affected. Will have no effect on the functionality of the input.
=> feat: updated error styling for input component

CHANGELOG.md, src/components/ViewingsList/utils.ts
Closes #L3-410
**Summary**
- Adding overlooked email labels to i18n
- `emaiLabel`
- `emailLinkLabel`
- `emailToggleLabel`
- New default text for `previewToggleLabel`
- New `previewToggleLabel` should read "Additional Hours"
- Email labels should accept new i18n values
=> Feature/L3-410 Chinese translations fixes

CHANGELOG.md, src/components/ViewingsList/ViewingsListCardForm.tsx
Closes #L3-432
**Summary**
- Moved Label field for primary viewing under 'hours 2'
- Renamed "Preview" toggle default to "Additional Viewings"
`ViewingsListCardForm.tsx`
- See that primary viewings label was moved
- See that Preview toggle label now reads "Additional Viewings"
=> L3-432 viewings widget label rearranging

src/components/ViewingsList/ViewingsListCardForm.tsx
[[L3-482](https://phillipsauctions.atlassian.net/browse/L3-382)]
**Summary**
Moving label fields back to top as before. 
`\seldon\src\components\ViewingsList\ViewingsListCardForm.tsx`
- Label fields have gloriously returned to the top of their respective sections
[L3-482]: https://phillipsauctions.atlassian.net/browse/L3-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> L3-382 - moving label fields back to top

src/components/ErrorBoundary/ErrorBoundary.tsx, src/components/LinkBlock/LinkBlock.tsx, src/utils/index.test.ts, src/utils/index.tsx
https://phillipsauctions.atlassian.net/browse/L3-2065
**Summary**
Nullish coalescing operator '??' has created an error in Phillips-public
Testing @babel/plugin-transform-nullish-coalescing-operator have not worked
Created a polyfill for Nullish coalescing operator
New Components
=> Chore: L3-2065 Revert Nullish Coalescing Operators in Seldon

src/components/Grid/_grid.scss, src/components/Header/_header.scss, src/components/HeroBanner/_heroBanner.scss, src/components/Input/_input.scss, src/components/Toggle/_toggle.scss, src/design/grid-tokens/_grid-tokens.scss, src/scss/_typography.scss, src/scss/_vars.scss, stylelint.config.cjs
[L3-2064](https://phillipsauctions.atlassian.net/browse/L3-2064)
**Summary**
Style lint was formatting sass in a way that was breaking Phillips-public deprecated sass compiler (glup-sass)
Config file was changed to prevent future sass breaking changes
Refactored code to match Phillips-public deprecated sass compiler
Legacy setting used:
color-function-notation 
media-feature-range-notation
New Components
[L3-2064]: https://phillipsauctions.atlassian.net/browse/L3-2064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chore: L3-2064 Change Seldon prettier config to be compatible with Phillips-public deprecated sass compiler

src/components/Header/Header.stories.tsx, src/components/UserManagement/UserManagement.stories.tsx, src/components/UserManagement/UserManagement.test.tsx, src/components/UserManagement/UserManagement.tsx, src/components/UserManagement/_userManagement.scss, src/components/UserManagement/types.ts, src/index.ts
BREAKING CHANGE: The  `UserManagement` `isLoggedIn` property has been replaced with the `authState` property
[L3-2972](https://phillipsauctions.atlassian.net/browse/L3-2972)
| ![image](https://github.com/user-attachments/assets/75eff643-0379-464c-b4bf-2e3e1a3e92c8) | ![image](https://github.com/user-attachments/assets/197f9c7c-6e3c-4fba-b79a-c38f7f2aec65) |
**Summary**
Because of CDN caching requirements, we need for our UserManagement panels LoggedIn/LoggedOut state to be determined client-side only after JavaScript hydrates.  This means we need to add a "Loading" state to the UserManagement panel.
- change(UserManagement): Switch `isLoggedIn` to `authState` enum …
=> feat(usermanagement)!: L3-2972 add a loading auth state

.gitignore, .vscode/launch.json, .vscode/settings.json, src/componentStyles.scss, src/index.ts, src/scss/_allPartials.scss, src/scss/_type.scss, src/scss/_typography.scss
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-3127)
**Summary**
If a downstream consumer only imported the `componentStyles.scss` the fonts would not be loaded.  We want component styles to be fully functional without requiring consumers to import `allPartials.scss`
- change(componentStyles): bring in the fonts
- change(allPartials): don't bring in the fonts here
- change(type): move the mixins here that were in typography so it's only fonts
- change(typography): move the mixins from this file to the type file
- `npm run build`
- `npm link`
Go the remix project
`npm link @phillips/seldon`
Remove the seldon `allPartials` import from the `allPartials.scss` …
=> fix(styles): L3-3127 need to import fonts from the main componentStyles

src/components/Accordion/Accordion.stories.tsx, src/components/Accordion/Accordion.test.tsx, src/components/Accordion/Accordion.tsx, src/components/Accordion/types.ts, src/components/Accordion/utils.ts, src/components/Footer/Footer.stories.tsx
[L3-3274](https://phillipsauctions.atlassian.net/browse/L3-3274)
| ![L3-3274 - before](https://github.com/user-attachments/assets/56a6c727-34af-436e-b7a9-02b1ea754b36) | ![L3-3274 - after](https://github.com/user-attachments/assets/fad1c3b8-72f8-44e3-9f11-dcee3590ecc6) |
**Summary**
Fixes the console error coming from the Accordion component. The error was a little misleading, it was complaining about the `collapsible` prop being passed to the DOM as a boolean instead of a string, but the error was actually caused by the fact that we didn't need to pass in the `collapsible` prop at all because the Accordion `type` was set to `multiple`. When the prop is `multiple`, the child components are already set to be collapsible, …
=> fix(accordion): L3-3274 add "variant" prop to Accordion

src/components/Accordion/Accordion.test.tsx, src/components/Accordion/AccordionItem.tsx, src/components/Accordion/_accordion.scss, src/components/Accordion/types.ts, src/components/Accordion/utils.ts
[L3-3439](https://phillipsauctions.atlassian.net/browse/L3-3439)
| https://github.com/user-attachments/assets/49ae04b5-010a-4ca5-bfab-c3458085baca | https://github.com/user-attachments/assets/dd5fa1eb-d45f-4f57-b334-f535fa9d00ee |
**Summary**
I updated the Accordion component to fix the behavior of the icons when sections are expanded and collapsed. Previously, they were relying on custom logic to determine the "collapsed" state of each panel, but there is an attribute that radix already uses to determine the collpased state, `data-state="open"` and `data-state="closed"`. I just rendered the icons in the component and use css and the `datta-state` to determine which one to hide and which one to show.
**Change List …
=> fix(accordion): L3-3439 accordion fixes

src/build/buildUtils.ts, src/componentStyles.scss, src/components/ContentPeek/ContentPeek.stories.tsx, src/components/ContentPeek/ContentPeek.test.tsx, src/components/ContentPeek/ContentPeek.tsx, src/components/ContentPeek/_contentPeek.scss, src/components/ContentPeek/index.ts, src/index.ts, src/patterns/ReadMore/index.ts, vite.config.ts
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-3777)
**Summary**
When I reorganized the component into `components` `patterns` and `site-furniture` our build process didn't transform all those new files correctly and led to consumer build failures. This change makes the transform process locate scss files in ANY new subdirectory. After the initial reorganization I got feedback from design that the "ReadMore" component should instead be called "ContentPeek" and a "component" rather than a "pattern"
- change(buildUtils): better logging and support all directories not just `/src/components`
- change(componentStyles): flip `patterns/ReadMore` to `components/ContentPeek`
- change(ReadMore): change …
=> fix(build): L3-3777 build process not handling new patterns and site-furniture

src/components/Accordion/_accordion.scss, src/components/Breadcrumb/_breadcrumb.scss, src/components/Button/_button.scss, src/components/DatePicker/_datePicker.scss, src/components/Input/_input.scss, src/components/Navigation/NavigationItem/_navigationItem.scss, src/components/Pagination/_pagination.scss, src/components/Search/_search.scss, src/components/SplitPanel/_splitPanel.stories.scss, src/design/Welcome.mdx, src/design/colors-tokens/_color-card.scss, src/design/type-tokens/_text-showcase.scss, src/design/type-tokens/type-tokens.mdx, src/pages/_page.scss, src/scss/_type.scss, src/story-styles.scss, stylelint.config.cjs
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-3693)
| ![image](https://github.com/user-attachments/assets/5f48ee33-71dc-4d6d-a725-f11f2ff82225) | ![image](https://github.com/user-attachments/assets/e745b8f3-ac1c-4183-b733-2bbed6f55bc9) |
**Summary**
Font-weight > 500 looks incorrect with variable fonts on Safari
- change(*.scss): change `font-weight` to use variable font  `wght` property instead
- change(type-tokens): remove some redundant examples
- change(eslint): put in rule to prevent future `font-weight` props
- Open the "Type Tokens" story on Safari, verify any font-weight: 600 or font-weight: …
=> fix(boldedFonts): L3-3693 variable font weight not working in Safari

src/components/Carousel/CarouselItem.tsx, src/components/Modal/Modal.tsx
[L3-3145](https://phillipsauctions.atlassian.net/browse/L3-3145)
**Summary**
follow ons from comments in https://github.com/PhillipsAuctionHouse/phillips-public-remix/pull/369
New Components …
=> chore(lotdetails): L3-3145 lot details seldon follow ons

src/components/Breadcrumb/Breadcrumb.stories.tsx, src/components/Breadcrumb/Breadcrumb.test.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/components/Breadcrumb/BreadcrumbItem.tsx, src/components/Breadcrumb/_breadcrumb.scss, src/components/Drawer/Drawer.tsx, src/components/IconButton/_iconButton.scss, src/components/Modal/Modal.tsx, src/components/Modal/_modal.scss, src/components/Pagination/Pagination.stories.tsx, src/components/Pagination/Pagination.test.tsx, src/components/Pagination/Pagination.tsx, src/components/Pagination/_pagination.scss, src/components/Pagination/utils.tsx, src/index.ts
[Jira Ticket ID](https://phillipsauctions.atlassian.net/browse/L3-3900)
| Truncates Too Early | Uses full available width |
| ![image](https://github.com/user-attachments/assets/d2a33e94-5dd2-4d3b-ab34-043367582ad6) | ![image](https://github.com/user-attachments/assets/89a5bd7e-0b2e-4777-b874-29e8a5c17a8a) |
**Summary**
Changes the prop model for `Breadcrumb` to  remove the capability to truncate at a character length as this doesn't use the full space available for the Breadcrumb at responsive screen sizes before truncating.  It instead uses css ellipsis overflow to do this so if there is room to show the full text we do.  In addition truncating at the character count is bad for accessibility because screen readers …
=> fix(breadcrumb): L3-3900 breadcrumb style fixes

src/components/Accordion/_accordion.scss, src/scss/_utils.scss, src/site-furniture/Header/_header.scss
[L3-3154](https://phillipsauctions.atlassian.net/browse/L3-3154)
| ![image](https://github.com/user-attachments/assets/75b7906e-ccde-43f3-8ab6-c1daa03e37bb) | ![image](https://github.com/user-attachments/assets/60c86b8c-27d9-4dbf-9a88-37193b4df10a) |
**Summary**
While adding the Lot Details Accordion to Remix, I noticed that the accordion Label styles didn't match the Figma
- change(accordion): fix fonts, colors and icon sizes for the AccordionItem
- change(utils): make it support both `$size-sm` or `$breakpoint-sm` because I keep getting confused and it fails silently
- change(header): need to make the accordion icons bigger just for the mobile header …
=> fix(accordion): L3-3154 accordion label and icon style fixes

src/components/Accordion/_accordion.scss
[L3-3154](https://phillipsauctions.atlassian.net/browse/L3-3154)
| ![image](https://github.com/user-attachments/assets/9cfa0c7d-87c8-40c8-bdca-ea54ee0c5b9d) | ![image](https://github.com/user-attachments/assets/5f3d8126-944c-4b3f-9834-8c7977424cd5) |
**Summary**
I regressed this style when I flipped to font variation settings instead of font-weight, this undoes that font variation setting for content and let the <strong> tag font-weight take over.
- change(accordion.scss): remove unnecessary font variation settings
- Verify if you put <strong> content in an accordion it renders as bols
- (Optional) Add …
=> fix(accordion): L3-3154 accordion item style was overriding <strong tags in CMS content

src/components/Tabs/Tabs.test.tsx, src/components/Tabs/TabsContent.tsx
[L3-4919](https://phillipsauctions.atlassian.net/browse/L3-4919)
**Summary**
Because the `aria-hidden` property was set on the `<TabContent` panel, screen readers were not being notified that the content being shown to the user was within a "tabpanel" role.
- change(TabsContent): remove aria-hidden
- change(Tabs.test): add test assertions to check for the tabpanel roles
- If the testcases pass it's working since they verify accessibility now
- Verify the keyboard navigability of the Tab story still functions
New Components
[L3-4919]: …
=> fix(tabpanel): L3-4919 tab component was hiding the tabpanel role from screen readers

src/components/Text/Text.test.tsx, src/components/TextSymbol/TextSymbol.stories.tsx, src/components/TextSymbol/TextSymbol.test.tsx, src/components/TextSymbol/TextSymbol.tsx, src/components/TextSymbol/_textSymbol.scss, src/components/TextSymbol/types.ts, src/components/TextSymbol/utils.test.ts, src/components/TextSymbol/utils.ts
[L3-5094](https://phillipsauctions.atlassian.net/browse/L3-5094)
| ![image](https://github.com/user-attachments/assets/9daef98f-9a3a-49fd-bc61-89d36749096d) | ![image](https://github.com/user-attachments/assets/926e05b4-ca66-4a49-9390-11241ee5e944) |
**Summary**
Some of the symbols we support are way too small in our font, this fix tries to normalize their size better so they're readable
- change(TextSymbol): switch `children` prop to `symbols` array since I have to examine each one and adjust its size
- change(_textSymbol.scss): add 3 size classes
- change(utils.ts): helper function to figure out which symbol is which size.
**Acceptance Test (how to verify the …
=> fix(textsymbol): L3-5094 normalize symbol size

src/components/Tabs/TabTrigger.tsx, src/components/Tabs/_tabs.scss
[L3-4707](https://phillipsauctions.atlassian.net/browse/L3-4707)
| ![ea2f0ca4-68b3-4650-bfc9-4cf56f89a6db](https://github.com/user-attachments/assets/65ab9aaf-1e95-472f-be8d-37aab1cc95b1)| ![Screenshot 2025-01-23 121134](https://github.com/user-attachments/assets/223a7a42-cf9a-41b5-a10c-0115e8b4532a) |
**Summary**
Fixed tabbing functionality and corrected focus styles
- Adjusted padding for tab content
- Added tabIndex to TabTrigger component
- Verify that outline only shows when tabbing through tabs and not on click of the tab
New Components
[L3-4707]: …
=> fix(tabs): L3-4707 Remove Focus Border From Tabs on Click

src/patterns/BidSnapshot/BidSnapshot.tsx, src/patterns/BidSnapshot/_bidSnapshot.scss
[L3-4432](https://phillipsauctions.atlassian.net/browse/L3-4432)
|
|
|
**Summary**
- Minor styling adjustments to the countdown section in BidSnapshot, so the countdown doesn't overlap with other object tiles or spacers in a grid layout
- css changes in bidsnapshot.scss
- passing a flag in bidsnapshot.tsx
- See that BidSnapshot and ObjectTile components look as expected
- Verify that tiles look okay in grid layouts (auction page, in client portal - bids page and favorites page)
- Post logs, …
=> fix(bidsnapshot): L3-4432 My Account - Lot Tile Update

src/scss/_type.scss
[L3-5135](https://phillipsauctions.atlassian.net/browse/L3-5135)
| ----- | ----- |
| ![ab7c679c-087b-4aee-ad02-f5fb7e4ac96a](https://github.com/user-attachments/assets/5f507e50-5f0c-4a89-8f7e-0fd9f8bc1092) | ![Screenshot 2025-01-29 112719](https://github.com/user-attachments/assets/cb0fc5a4-aa0b-43df-a2e8-e8cba496f9c0) |
**Summary**
Adjusted the underline offset for links
This pull request includes a minor change to the `src/scss/_type.scss` file. The change updates the `underline` mixin to use a different spacing variable for the offset parameter.
Styling adjustment:
* [`src/scss/_type.scss`](diffhunk://#diff-2ee3e65f8a2cdd6cdfa290d38c5157311252d6888567ba85a750232523fb42fbL40-R40): …
=> fix(link): L3-5135 Fix Underline Spacing For Links

src/components/PageContentWrapper/_pageContentWrapper.scss, src/design/spacing-tokens/spacing-tokens.mdx, src/scss/_vars.scss
**L3-4620**
[L3-4620](https://phillipsauctions.atlassian.net/browse/L3-4620)
| Before bp-md | After bp-md |
| ![image](https://github.com/user-attachments/assets/088bf514-c0f4-4c54-bbbc-2857501b9ba0) | ![image](https://github.com/user-attachments/assets/a787176c-21c6-4b96-a8a9-dfddbd57300b) |
| Before bp-xl | After bp-xl |
| ![image](https://github.com/user-attachments/assets/9c831bfd-74f8-4f20-9d9d-4971cbdce958) | ![image](https://github.com/user-attachments/assets/99dd685b-f0f2-49a0-b1f1-4e4d59599c74) |
**Figma link**
https://www.figma.com/deck/hqJJvOsa9XrlafXAR9aiwS/EASEL-Foundation?node-id=9-889&viewport=-28375%2C-151%2C0.7&t=uPw9sTzQupBPYert-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1
**Summary**
Add high-level overview …
=> feat(_pageContentWrapper.scss): L3-4620 added new page wrapper and tokens

src/patterns/BidSnapshot/BidSnapshot.stories.tsx, src/patterns/BidSnapshot/BidSnapshot.test.tsx, src/patterns/BidSnapshot/BidSnapshot.tsx
[L3-5370](https://phillipsauctions.atlassian.net/browse/L3-5370)
| ![image](https://github.com/user-attachments/assets/00e159d4-c209-4844-81bc-5412d4bf7b9c) | ![image](https://github.com/user-attachments/assets/cd550aa7-8998-49e3-a635-2a05db09dd8f) 
**Summary**
If soldPrice is 0, but bids have occurred, we should be showing the `soldForText` and `wonForText` but hiding the sold price (i.e. soldPrice=0).  Previously we were hiding the whole sold section
Refinements in rendering logic:
* [`src/patterns/BidSnapshot/BidSnapshot.tsx`](diffhunk://#diff-023608454dd8a373f83e678913fe1db898600977d93505f7afa1ff759b3c3e59L146-R149): Change the rendering logic in the …
=> fix(bidsnapshot): L3-5370 sold price should still show text if sold price is hidden

src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/Input/_input.scss
[L3-5289](https://phillipsauctions.atlassian.net/browse/L3-5289)
**Summary**
This just adds an extra testcase and some more documentation to the `disabled` property of the `<Input` component
- Make sure the property comment for `disabled` shows in autocomplete inside VSCode
New Components
[L3-5289]: https://phillipsauctions.atlassian.net/browse/L3-5289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(input): L3-5289 add specific testcase for input readonly

src/components/Button/_button.scss, src/patterns/ObjectTile/_objectTile.scss, src/patterns/SaleHeaderBanner/_saleHeaderBanner.scss
[L3-5540 ](https://phillipsauctions.atlassian.net/browse/L3-5540)
Linked to this [PR](https://github.com/PhillipsAuctionHouse/phillips-public-remix/pull/821) in remix
|![Screenshot 2025-02-28 140856](https://github.com/user-attachments/assets/85627c41-3e1e-4336-bf02-816f6e05f40e) | ![Screenshot 2025-02-28 155125](https://github.com/user-attachments/assets/c6d35df0-3720-42ba-baa3-6ed1f8f8b2e3) |
**Figma link**
[Figma Link](https://www.figma.com/design/OvBXAq48blO1r4qYbeBPjW/RW---Sale-Page-(PLP)?node-id=147-16379&m=dev)
**Summary**
Tweaks to the styles in sale header banner
This pull request includes several changes to the SCSS files to improve the styling and …
=> fix(sale-header-banner): L3-5540 PLP Sale Header Banner Fixes

src/components/Article/Article.test.tsx, src/components/Button/Button.stories.tsx, src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/Input/Input.stories.tsx, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/Input/_input.scss, src/components/Text/Text.stories.tsx, src/components/Text/Text.test.tsx, src/components/Text/Text.tsx, src/patterns/HeroBanner/HeroBanner.test.tsx, src/scss/_sharedClasses.scss
[L3-5705](https://phillipsauctions.atlassian.net/browse/L3-5705)
**Summary**
Added skeleton for button, input and text
This pull request introduces a skeleton loading state to various components, enhancing the user experience by providing visual feedback while content is being loaded. The changes include updates to the `Button`, `Input`, and `Text` components, as well as their corresponding tests and stories.
* **Button Component:**
- Added …
=> feat(Input): L3-5705 added skeleton

src/components/GridItem/GridItem.stories.tsx, src/components/GridItem/GridItem.tsx, src/components/GridItem/_gridItem.scss, src/components/GridItem/gridItemUtils.ts, src/components/GridItem/types.ts, src/utils/index.tsx
[L3-6072](https://phillipsauctions.atlassian.net/browse/L3-6072)
**Summary**
When I started working on this ticket, I discovered that we didn't have a way to explicitly set `grid-column-start` for a `<GridItem />`, which meant we were unable to have empty columns in our layouts using the base `<Grid />` and `<GridItem />` components. There was some css we had in remix that was attempting to to fix the grid layout to achieve this, but it was being overwritten by the css coming from seldon.
To fix this, I added some props to GridItem (`*ColStart` for each breakpoint), and when they're used, it essentially just sets the `grid-column-start` value for that breakpoint.
I also added support for the `xl` breakpoint because we didn't previously have it and the design differed …
=> feat(Grid): L3-6072 Add support for xl breakpoints and colStart props

src/components/Icon/Icon.stories.tsx, src/components/Icon/Icon.test.tsx, src/components/Icon/Icon.tsx, src/components/Icon/_icon.stories.scss, src/components/Icon/index.ts, src/index.ts, src/utils/scssUtils.test.ts, src/utils/scssUtils.ts
[L3-3417](https://phillipsauctions.atlassian.net/browse/L3-3417)
**Summary**
Part 1/4 of the changes for the Sale and Lot icon changes. This PR adds the `Icon` component that will be used for rendering resizable and recolorable svgs.
This pull request introduces a new `Icon` component to the codebase, along with associated stories, tests, and utility functions for handling SCSS variables. The changes include the implementation of the `Icon` component, its stories for Storybook, unit tests, and updates to SCSS utilities and styles.
* [`src/components/Icon/Icon.tsx`](diffhunk://#diff-08acd9c461dd2b3858a54d0dd361b9164bdc650ee0050ace49c108d9dc6e2059R1-R57): Created the `Icon` component with support for height, width, …
=> feat(Icon): L3-3417 Part 1 - Add Icon component

src/components/Accordion/AccordionItem.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/components/Breadcrumb/BreadcrumbItem.tsx, src/components/Carousel/CarouselArrows.tsx, src/components/ContentPeek/ContentPeek.tsx, src/components/Drawer/Drawer.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Filter/Filter.tsx, src/components/Filter/FilterHeader.tsx, src/components/IconButton/_iconButton.scss, src/components/Modal/Modal.tsx, src/components/Pagination/Pagination.tsx, src/components/Pagination/_pagination.scss, src/components/Search/SearchButton.tsx, src/components/SeldonImage/SeldonImage.tsx, src/components/SeldonImage/utils.test.ts, src/components/SeldonImage/utils.ts, src/components/Select/Select.tsx, src/components/Tags/Tags.tsx, src/patterns/BidSnapshot/BidMessage.tsx, src/patterns/UserManagement/UserManagement.tsx, src/patterns/UserManagement/_userManagement.scss, src/site-furniture/Footer/Footer.tsx, src/site-furniture/Header/Header.tsx
[L3-3417](https://phillipsauctions.atlassian.net/browse/L3-3417)
**Summary**
Part 3/4 of the changes for the Sale and Lot icon changes. This PR handles all of the component updates to support the new `Icon` component
This pull request includes several updates to various components to standardize the use of the `Icon` component instead of directly importing SVG icons. This change enhances consistency and simplifies icon management across the codebase. Below are the most important changes grouped by theme:
* Replaced direct SVG imports (`LockIcon`, `MinusIcon`, `PlusIcon`) with the `Icon` component in `AccordionItem.tsx` to improve icon handling. [[1]](diffhunk://#diff-79f9c994e4003a75f85d4965935180c14141e3318cc85ee0688 …
=> feat(Icon): L3-3417 Part 3 - component updates

src/components/Carousel/Carousel.stories.tsx, src/components/Carousel/Carousel.test.tsx, src/components/Carousel/CarouselDots.tsx, src/components/DatePicker/DatePicker.test.tsx, src/components/DatePicker/DatePicker.tsx, src/components/Drawer/Drawer.stories.tsx, src/components/Input/Input.tsx, src/components/Pagination/Pagination.tsx, src/components/PinchZoom/PinchZoom.stories.tsx, src/components/Select/Select.tsx, src/patterns/Subscribe/Subscribe.test.tsx, src/patterns/Subscribe/Subscribe.tsx, src/scss/_vars.scss, src/site-furniture/Footer/Footer.test.tsx, src/utils/constants.ts, src/utils/index.tsx
[L3-6222](https://phillipsauctions.atlassian.net/browse/L3-6222)
https://github.com/user-attachments/assets/9631d0bb-cd2d-4ded-ae1f-6759a44c30c0
**Figma link**
**Summary**
Removed all `useId` from Seldon, make `id` required field. 
The newest version of Seldon is crashing on phillips-public
This crash happens because the React version in the Razor Phillips-public is not v18.3 it does not support the v18.3 React.useId()
https://www.nuget.org/packages/React.AspNet/
At first I tried to use UUID but that didn’t work either because the server-side rendering environment does not support the Web Crypto API, which includes the crypto.getRandomValues() method in UUID.
The work around is to remove the React.useId() …
=> fix(upgrade): L3-6222 allow seldon to be used with phillips-public older React 18 version

src/components/GridItem/GridItem.stories.tsx, src/components/GridItem/GridItem.tsx, src/components/GridItem/_gridItem.scss, src/components/GridItem/gridItemUtils.ts, src/utils/index.tsx
This reverts commit a447d79f47303770ca21ffc10a56fca88a946e8a.
**Summary**
This broke our grids in Remix because they assume that cols will be laid out to fill the available grid columns without specify a grid colum start property.
- Check the Grid Item stories
New Components
=> fix(Grid): L3-6072  Revert Add support for xl breakpoints and colStart props (#564)"

src/components/Icon/Icon.test.tsx, src/utils/scssUtils.test.ts, src/utils/scssUtils.ts
[L3-6336](https://phillipsauctions.atlassian.net/browse/L3-6336)
| ![image](https://github.com/user-attachments/assets/ecab2f36-0233-480f-b3bd-32014da2fb01) | ![image](https://github.com/user-attachments/assets/3fb31b22-23b7-4205-aa15-396481482b5e) |
**Figma link**
**Summary**
Fixes an issue that was caused by the fact that the function responsible for setting the default color wasn't working properly. Now all `Icons` will have a default color of `$pure-black` aka (#000000) unless otherwise specified.
This pull request includes changes to improve the handling of SCSS variables in the `Icon` component and its …
=> fix(Icons): L3-6336 fix fallback value for Icon color

src/patterns/ObjectTile/ObjectTile.tsx, src/patterns/ObjectTile/_objectTile.scss
[L3-6251](https://phillipsauctions.atlassian.net/browse/L3-6251)
**Summary**
We've been seeing hydration errors for a long time intermittently in Remix.  These seem to be [caused](https://nextjs.org/docs/messages/react-hydration-error#common-causes) by HTML that does not match the HTML specification being rendered server side.  Specifically trying to nest a `<div` in a `<p` element.  
This pull request includes changes to the `ObjectTile` component in both `ObjectTile.tsx` and `_objectTile.scss` files. The primary goal of these changes is to update the `Text` component elements from `p` to `span` and ensure proper display styling for various elements.
* Updated the `Text` component elements from `p` to `span` for …
=> fix(lotobjecttile): L3-6251 incorrect HTML nesting causing HTML validation errors and hydration errors

src/components/Button/Button.test.tsx, src/components/Button/Button.tsx
[L3-6129](https://phillipsauctions.atlassian.net/browse/L3-6129)
**Summary**
The `modulepreload-link` doesn't actually live at `href`, it lives at some remix specific location `href/asset2343something.js`, which doesn't make sense to calculate in seldon
perhaps there is a more sophisticated change we could make where we pass in the remic `Link` component from the consumer, but for now we should just remove the `<link>` tag which is throwing the error
- Remove the `modulepreload-link` tag from the button
- No more console log errors when using the lot navigator in remix
- (Optional) Add verification steps to make sure this PR doesn't break old …
=> fix(prefetching): L3-6129 remove module <link>

src/components/Countdown/Countdown.tsx, src/patterns/BidSnapshot/BidSnapshot.tsx
[L3-6379](https://phillipsauctions.atlassian.net/browse/L3-6379)
**Summary**
Add a `currentDateTime` prop to the `Countdown` and `BidSnapshot` components to override `new Date()`, when we don't want to rely on the user's machine time
This pull request introduces enhancements to the `Countdown` and `BidSnapshot` components by adding support for a `currentDateTime` prop, which improves testability and allows external control of the current time. The changes also include adjustments to internal logic to utilize this new prop.
* Added a new optional `currentDateTime` prop to the `CountdownProps` interface. (`[src/components/Countdown/Countdown.tsxR46](diffhunk://#diff-9e886c1eb76bd42362402a2c88d7e3ee8c39be450c5d465c96b860 …
=> feat(countdown): L3-6379 allow custom currentDate prop

src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx, src/components/Modal/_modal.scss
[PHOENIX-2058](https://phillipsauctions.atlassian.net/browse/PHOENIX-2058)
| <img width="300" height="318" alt="Screenshot 2025-07-22 at 10 49 03 PM" src="https://github.com/user-attachments/assets/0208d45d-f250-4f6e-9048-f0734cdc3c98" /> | <img width="376" height="386" alt="Screenshot 2025-07-22 at 10 48 09 PM" src="https://github.com/user-attachments/assets/70599310-5109-47fe-b668-7b242fdaddb4" /> |
**Figma link**
[Figma Link](https://www.figma.com/board/XLadic4iRNVzGE8JP3XGjZ/Overview-of-Mobile-Bidding-Changes-11Mar2025?node-id=4-18700&t=4xNFA883EsffV6h0-4)
**Summary**
Added close icon prop and positioning
This pull request introduces a new feature for the …
=> feat(Modal): PHOENIX-2058 adding custom icon to modal

src/patterns/FavoritesCollectionTile/FavoritesCollectionTile.stories.tsx, src/patterns/FavoritesCollectionTile/FavoritesCollectionTile.test.tsx, src/patterns/FavoritesCollectionTile/FavoritesCollectionTile.tsx, src/patterns/FavoritesCollectionTile/_favoritesCollectionTile.scss
[L3-7093](https://phillipsauctions.atlassian.net/browse/L3-7093)
| ![image](https://github.com/user-attachments/assets/e77c371b-3567-45c6-8463-02f532f7f238) | ![image](https://github.com/user-attachments/assets/3c6f75e5-d211-46b4-b06b-898ff03893fd) |
| ![image](https://github.com/user-attachments/assets/93e16b76-0b81-4755-bda1-f4e6cb3cfdd0) | ![image](https://github.com/user-attachments/assets/d589b379-ee82-48f7-bc75-8743cf3b11b4) |
**Figma link**
[Figma Link](https://www.figma.com/design/rIefa3bRPyZbZmtyV9PSQv/My-Account?node-id=75-19784&m=dev)
**Summary**
Updating the Favorites Collection Tile for style and accessibility: 
- Background of lot object tile in favorites collection tile should be gray, object contain
- …
=> feat(favoritesCollectionTile): L3-7093 favorites collection tile fixes

src/patterns/SaleCard/SaleCard.stories.tsx, src/patterns/SaleCard/SaleCard.tsx, src/patterns/SaleCard/_saleCard.scss
[L3-7429](https://phillipsauctions.atlassian.net/browse/L3-7429)
**Figma link**
[Figma Link](https://www.figma.com/design/H1kCh6MXU8jasYbQuCbyBt/Calendar?node-id=5470-51467&m=dev)
**Summary**
Updates the SaleCard to be more responsive and rely on flexbox for sizing the image and detail sections
This pull request updates the `SaleCard` component and its related stories to improve image quality, adjust conditional rendering for CTAs, and add styling for CTA containers. The most significant changes are grouped below:
**Image quality improvements in storybook examples:**
* Updated the `imageSrc` in all `SaleCard` story variants to use a higher-resolution image (`https://picsum.photos/800/450` instead of …
=> feat(SaleCard): L3-7429 make sale card more responsive
